### ISSUE TITLE
SPARQL queries for templates not correctly visualized

### ISSUE THREAD

**Issue by m1ci** [freme-project/freme-project.github.io#100]
In the list of templates
http://api-dev.freme-project.eu/doc/api-doc/list-templates.html
the SPARQL queries are not correctly visualized. E.g. the template with name "Authors born in place" has SPARQL:

```
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX ore: <http://www.openarchives.org/ore/terms/>
CONSTRUCT {  ?person  <http://rdvocab.info/ElementsGr2/placeOfBirth> <@@@entity_uri@@@> ;  }
WHERE {  ?person  <http://rdvocab.info/ElementsGr2/placeOfBirth> <@@@entity_uri@@@> ;  } LIMIT 10
```

but the docs show only:

```
PREFIX edm:  PREFIX ore:  CONSTRUCT {  ?person   <@@@entity_uri@@@> ;  } WHERE {  ?person   <@@@entity_uri@@@> ;  } LIMIT 10
```

**Comment by jnehring** [comment]
The problem is that in a string like `PREFIX edm: <http://www.europeana.eu/schemas/edm/>` the part in between brackets is interpreted as HTML tag.

@josauder please add HTML encoding to the Javascript codes.
