### ISSUE TITLE
Document new parameters in Tildes API

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#102]
Write changes for the documentation of e-Terminology and e-Translation in this issue. Then assign the issue to @josauder so he can implement the changes.

**Comment by andish** [comment]
For FREME 0.4 there are some new  parameters.
For `POST /e-terminology/tilde`

| Parameter | Input Type | Description | Parameter type | Data type |
| --- | --- | --- | --- | --- |
| `collection` | textbox | collection id from https://term.tilde.com portal. If filled then annotates only with terms from that collection | query | string |
| `mode` | Picklist(full/annotation) with value='full' as selected | Whether the result must contain full terminology information or only term annotations with references to the full information | query | string |

For `POST /e-translation/tilde`

| Parameter | Input Type | Description | Parameter Type | Data Type |
| --- | --- | --- | --- | --- |
| `domain` | textbox | specify domain of translation system. List of supported domains and language pairs can be found here: https://services.tilde.com/translationsystem | query | string |
| `system` | textbox | select translation system by ID [an alternative to source, target language and domain selection]. ID of public translation system can be retrieved at https://services.tilde.com/translationsystems  or private system ID can be found at portal http://tilde.com/mt with authentication [optional, if omitted then source and target languages and also domain parameters are used] | query | string |

**Comment by jnehring** [comment]
@josauder please wait for https://github.com/freme-project/Broker/issues/125 before you implement these changes.

**Comment by jnehring** [comment]
@andish I wonder: Why is there no documentation for the parameter "key"?

**Comment by andish** [comment]
@jnehring true, it is now missing from documentation. I thought that there is some implementation of token/key store in broker when was speaking about tokens, but this can be done also by implementing as new query parameter.

@josauder, please, add new  params:

For `POST /e-terminology/tilde`

| Parameter | Input Type | Description | Parameter type | Data type |
| --- | --- | --- | --- | --- |
| `key` | textbox | A private key to access private and not publicly available terminology collections. Key can create here: https://term.tilde.com/account/keys/create?system=Freme. Optional, if omitted then annotates only with standartized and other public collections | query | string |

For `POST /e-translation/tilde`

| Parameter | Input Type | Description | Parameter type | Data type |
| --- | --- | --- | --- | --- |
| `key` | textbox | A private key to access private and not publicly available translation systems. Key can be created by contacting Tilde team http://www.tilde.com/mt/contacts. Optional, if omitted then translates with public systems | query | string |
