### ISSUE TITLE
update 3rd party library list for documentation

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#103]
Please update the [table sheet FREME-0.4](https://docs.google.com/spreadsheets/d/1j2XPwjRLTjyxFm0ceFf_Ts1tmigZEc-YatAWEaciz8k/edit#gid=397366127) concerning documentation:
- add rows for libraries, which are used by documentation
- write the keyword "KEEP" into the field: [`<libraryRow>`, `documentation`]. This marks the library as manually added to the Freme project `documentation`
- if there is no template for a special license, please create and add one to the [template folder](https://github.com/ArneBinder/MavenApacheLicenseUtil/tree/master/src/main/resources/templates).

Perhaps, have a look at step 2 of the "workflow" in this [readme](https://github.com/ArneBinder/MavenApacheLicenseUtil#the-workflow-is-as-follows).

When finished, assign to @ArneBinder.

**Comment by josauder** [comment]
What exactly do you mean? I added Jekyll (the static site generator), but in https://github.com/freme-project/Documentation/issues/56 you say

> Get list of dependencies from source code / html head of http://api-dev.freme-project.eu/doc/

Which makes it sound like you want to add JS libraries like jQuery to the 3rd Party licenses?

**Comment by jnehring** [comment]
@josauder please compile a list of 3rd party libraries like jquery, jquery plugins and jekyll and so on that you use and add them to above mentioned table.

**Comment by josauder** [comment]
Added in anything I could find. The format of the table is awkward for non-maven / non-java dependencies.
There is no source for the jquery.slideto plugin. I created an issue at [swagger-ui](https://github.com/swagger-api/swagger-ui/issues/1711), will update if anybody replies.

**Comment by ArneBinder** [comment]
> The format of the table is awkward for non-maven / non-java dependencies.

@josauder Any solutions? Feel free to improve the tool. For further information concerning the table columns: the output line in the 3rd-party-licences file is generated according to [this method](https://github.com/ArneBinder/MavenApacheLicenseUtil/blob/master/src/main/java/licenseUtil/LicensingObject.java#L120-L157).
But the program which generates and processes the table is called MavenPacheLicenseUtil. That it handles non-maven projects is just a necessary addition, not the focus.
