### ISSUE TITLE
Tutorial: How to write a tutorial

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#104]
https://docs.google.com/document/d/15PDwUrs2dTAC8z584bzdzbsngOO8Jl_9pfTGGSDfqWo/edit#

**Comment by m1ci** [comment]
1) can you prepare a documentation page for each tutorial?
2) can you also include actual implementation with input form and button? - so that we dont spend much time on this.

**Comment by jnehring** [comment]
We will create a demo tutorial. This will explain how to create the page, demo implementation, ... It will be finished today or tomorrow

**Comment by jnehring** [comment]
Done: http://api-dev.freme-project.eu/doc/tutorials/how-to-write-tutorials.html
