### ISSUE TITLE
Knowledge base article: How to integrate an external service into FREME

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#105]

**Comment by jnehring** [comment]
I created the article: http://api-dev.freme-project.eu/doc/tutorials/implement-eservice.html

But it creates a 2nd menu "Tutorials". @josauder can you help me? Something went wrong...

**Comment by josauder** [comment]
You put `pos: 7.2` in the yaml-header so jekyll was trying to put your tutorial after (on the very right of) every existing document. The correct `pos` for `Tutorials` is 3.x
