### ISSUE TITLE
Write XLIFF roundtripping tutorial

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#106]
Recognizing entities in XLIFF content (relies on e-Internationalisation roundtripping)

See [How to write a tutorial](http://api-dev.freme-project.eu/doc/tutorials/how-to-write-tutorials.html)

**Comment by borriellom** [comment]
Tutorial now available in the Documentation.
Just a note: roundtripping for XLIFF files is not supported. So the tutorial explains how to retrieve entities from a XLIFF 1.2 file. The output can be either in turtle or json-ld formats.
