### ISSUE TITLE
Write tutorial: Recognizing entities using a selected data set

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#107]
See [How to write a tutorial](http://api-dev.freme-project.eu/doc/tutorials/how-to-write-tutorials.html)

**Comment by m1ci** [comment]
deadline?

**Comment by jnehring** [comment]
The [notes of last developer call](https://docs.google.com/document/d/1-A2arIP5Rjxw_b-Mq_7602eAnFyn9ok1tvx6oeG0zL4/edit?usp=drive_web) say the deadline for the drafts is 5th of november. And deadline for the article itself is EDF on 15th november.

**Comment by m1ci** [comment]
done, see http://api-dev.freme-project.eu/doc/tutorials/entity-recognition-against-custom-dataset.html
