### ISSUE TITLE
Write tutorial: Create an eBook using existing HTML content

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#108]
See [How to write a tutorial](http://api-dev.freme-project.eu/doc/tutorials/how-to-write-tutorials.html)

**Comment by pheyvaer** [comment]
The (draft) tutorial can be found [here](http://api-dev.freme-project.eu/doc/tutorials/html-to-epub.html).

**Comment by jnehring** [comment]
Thank you. Since the tutorial is only a draft and needs some further work I reopen the issue so we keep track of this task.

I like how you added line numbers to the source codes. Did you manually create this or did you use a library or markdown?

**Comment by m1ci** [comment]
> I like how you added line numbers to the source codes. Did you manually create this or did you use a library or markdown?

http://hilite.me/

**Comment by josauder** [comment]
The link at the very bottom is broken:

```
The result can also be downloaded <a href="https://drive.google.com/open?id=0B-qMtkPK-unYaEFtS1Y5UmgxeGs">here</a>.
```

It leads to a not-found page

**Comment by pheyvaer** [comment]
@jnehring can we still edit or do we need to wait until 0.5?

**Comment by jnehring** [comment]
We will release the documentation homepage on thursday 12th. So you can still edit it.

**Comment by pheyvaer** [comment]
@josauder I checked and I can download the file (even when not logged in with a Google Account).

**Comment by josauder** [comment]
My bad. It works for me too, it was just a browser setting I had wrong.
