### ISSUE TITLE
Write tutorial: Translate XLIFF 2.0 content from French to English

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#109]
See [How to write a tutorial](http://api-dev.freme-project.eu/doc/tutorials/how-to-write-tutorials.html)

**Comment by borriellom** [comment]
Tutorial now available in the Documentation. 
Just a couple of notes: e-Internationalization doesn't support XLIFF 2.0 at the moment and e-Translation doesn't support translations from French to English.
So the tutorial explains how to translate a XLIFF 1.2 file from English to French.
