### ISSUE TITLE
Add general text to each e-Service

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#11]
We should add a text to each e-Service (e-link, e-entity, ...) to give a general explanation about this service.

I remember that it is possible to write a text next to the heading but that looks like a subheading. We should try to manipulate the CSS in order to change it into a normal text.

So the first step is to find out if the CSS hack works. When the first step workend then in the second step I send you the texts for each e-Service and you integrate it.

**Comment by jnehring** [comment]
Take the e-Service descriptions from http://api.freme-project.eu/doc/0.6/knowledge-base/freme-for-sysadmins/e-services.html as text.

e-Entity: Detect named entities in text. The service performs named entity recognition, classification and linking. The service also supports the upload of custom datasets for linking.
e-Link: Enrich data with contents from the Linked Open Data cloud.
User: User management APIs to create, read, update, delete users and create authentication tokens. More information in the LINK authentication article.
toolbox: Configure postprocessing filters that can be used to LINK simplify output. Further use the LINK converter endpoint to convert various document formats into NIF.
pipelining: Configure workflows and share the workflows with other users using FREMEs pipelining API.

**Comment by ArneBinder** [comment]
TODO: 
- fix converter endpoint link
- fix simple api doc

**Comment by ArneBinder** [comment]
Implemented, except "fix nif-converter endpoint link" (no trivial solution found).
