### ISSUE TITLE
general comments on the structure of the documentation page

### ISSUE THREAD

**Issue by m1ci** [freme-project/freme-project.github.io#114]
1) IMO "FREME-Showroom" and "Tutorials" is the same. Both sections are providing how-to examples. Maybe the Showroom was meant to provide possible "Use case" examples?

2) The name for the section "Knowledge Base" is misleading. I would think that there I can find some FREME dataset (or knowledge base) for download or use. Since it is providing technical info, I suggest renaming this section to "Getting Started" or similar.

3) The API documentation page http://api-dev.freme-project.eu/doc/api-doc/full.html primarily describes the input and output parameters for each service. However, there is not description of the services. I could not find any description of the services in the whole documentation. I suggest to provide short description (1 paragraph) for each e-Service early in the API documentation page. So a potential user, which visits this page for first time, immediately find information what every service can do.

**Comment by jnehring** [comment]
Thanks for the input!

> 1) IMO "FREME-Showroom" and "Tutorials" is the same

You are right. We will delete the tutorial like examples that we have in the showroom right now. In the showroom we are going to put a screencast of the editor GUI that iMinds created and maybe more screencasts / screenshots of tools build with freme.

> 2) The name for the section "Knowledge Base" is misleading

Knowledge base is meant to be a series of articles around all kinds of FREME stuff. But Im open to other names. Just "Getting started" does not sound right to me.

> 3) The API documentation page http://api-dev.freme-project.eu/doc/api-doc/full.html primarily describes the input and output parameters for each service. However, there is not description of the services

I agree. Unfortunately swagger does not let us write an introductionary text to each e-Service category in the default configuration. We have to modify the swagger templates to do that. We already figured out how that technology works and we are preparing a list of improvements we want to do when we modify the templates. This feature will come in a future release.

**Comment by josauder** [comment]
> Unfortunately swagger does not let us write an introductionary text to each e-Service category in the default configuration. We have to modify the swagger templates to do that. 

@jnehring under the current version we can add descriptions to each individual e-Service. If you look closely, the `General Information` Tag is just an "empty e-service" only containing a description. If anybody were to provide introductory paragraph, they could be added very easily.
