### ISSUE TITLE
Update e-Link documentation

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#115]
Please write documentation for http://api-dev.freme-project.eu/doc/api-doc/full.html#!/e-Link/createTemplate and document the parameters `type` and `visibility`. Update the JSON example also. Then assign the issue to @josauder so he can implement the changes in the API Documentation.

**Comment by ArneBinder** [comment]
From now on the input JSON can include the following new entries (this holds for POST and PUT):
- endpointType: This parameter describes the type of the endpoint data. The value has to be either "sparql" (default) or "ldf".
- visibility: This parameter controlls, how the template can be accessed by other users than the owner. This includes enrichment etc. via this template. See the Restricted Endpoints and Restricted Resources section [of this article](http://api-dev.freme-project.eu/doc/knowledge-base/authentication.html) for further information. The value has to be either "public" (default) or "private".

new example json:

```
 {
 "query":"a SPARQL CONSTRUCT query",
 "endpoint":"the SPARQL endpoint which will be used to execute the template",
 "label":"the title of the template",
 "description":"a description of the template",
 "endpointType":"sparql",
 "visibility":"public"
 } 
```

Furthermore `PUT /e-link/templates/{templateid}` gets the optional api parameter `owner`: this has to be the name of an existing user.
There are no other new broker api parameter, visibility was moved to Template, like endpointType.

@josauder could you link the Restricted Resources/Endpoint sections in the article mentioned above directly?

**Comment by ArneBinder** [comment]
updated swagger entry (please reformat, if necessary. I'm not into swagger syntax anymore):

```
Creates a new enrichment template.  \n\n
The input has to contain the following entries:\n\n
query: a SPARQL CONSTRUCT query\n
endpoint: the SPARQL endpoint which will be used to execute the template\n
label: the title of the template
description: a description of the template

Optional entries:\n\n
endpointType: This parameter describes the type of the endpoint data. The value has to be either "sparql" (default) or "ldf".\n
visibility: This parameter controlls, how the template can be accessed by other users than the owner. This includes enrichment etc. via this template. See the Restricted Endpoints and Restricted Resources section of this article for further information. The value has to be either "public" (default) or "private".\n\n
        **Example of input in JSON format:**\n \n
        <pre lang=\"javascript\"><code>
        {\n
        \"query\":\"PREFIX dbpedia: &lt;http://dbpedia.org/resource/&gt;
PREFIX dbpedia-owl: &lt;http://dbpedia.org/ontology/&gt;
PREFIX rdf: &lt;http://www.w3.org/1999/02/22-rdf-syntax-ns#&gt;
PREFIX geo: &lt;http://www.w3.org/2003/01/geo/wgs84_pos#&gt;
CONSTRUCT
{
  ?museum &lt;http://xmlns.com/foaf/0.1/based_near&gt; &lt;@@@entity_uri@@@&gt; .
}
WHERE
{
    &lt;@@@entity_uri@@@&gt; geo:geometry ?citygeo .
    ?museum rdf:type &lt;http://schema.org/Museum&gt; .
    ?museum geo:geometry ?museumgeo .
    FILTER (&lt;bif:st_intersects&gt;(?museumgeo, ?citygeo, 10))
}
LIMIT 10\",\n
        \"endpoint\":\"http://dbpedia.org/sparql/\",\n
        \"label\":\"template title\",\n
        \"description\":\"template description\",\n
        \"endpointType\":\"sparql\",\n
        \"visibility\":\"public\"
        }
        </code></pre>\n
        Here is an example SPARQL COSTRUCT QUERY:\n
        <pre lang=\"sparql\"><code>
        PREFIX geo-pos: &lt;http://www.w3.org/2003/01/geo/wgs84_pos# &gt\n
        CONSTRUCT {\n
            &lt;@@@entity_uri@@@&gt geo-pos:lat ?lat .\n
            &lt;@@@entity_uri@@@&gt geo-pos:long ?long .\n
        } WHERE {\n
            &lt;@@@entity_uri@@@&gt geo-pos:lat ?lat .\n
            &lt;@@@entity_uri@@@&gt geo-pos:long ?long .\n
        }
        </code></pre>\n
        \n
        In fact, each template should have the field `@@@entity_uri@@@` which identifies an entity. When performing enrichment, the template is executed for each entity (identified with taIdentRef) in the document. It means, each `@@@entity_uri@@@` is replaced with the taIdentRef link from the submitted document for enrichment. So `@@@entity_uri@@@` us a reserved field name.\n
        \n
        However you can always introduce your fields e.g. `... } LIMIT @@@my_limit@@@` and then use this fields by submitting `my_limit` parameter in the request. Example (see `my_limit` parameter):\n
        <pre lang=\"bash\"><code>
        curl -v -d @example.ttl -X POST -H \"Content-Type: text/turtle\" \"http://localhost:8080/e-link/documents?templateid=116&my_limit=5\"
        </code></pre>
```

Please add the optional query parameter "owner" with this description:
If this parameter is not empty, the owner of the template will be changed. The value of this parameter has to be the name of an existing user.

Please link "... of this article" like descriped above.

**Comment by josauder** [comment]
Do the `visibility` and `endpointType` parameters also apply to PUT /templates/{templateid} ?
Or can one only update the template with all information in the body? If so - why does `owner` get its own query string?

**Comment by m1ci** [comment]
> Do the `visibility` and `endpointType` parameters also apply to PUT /templates/{templateid} ?
> 1) yes
> 2) small correction, its `type` and not `endpointType`
> 
> Or can one only update the template with all information in the body?

Yes.

> If so - why does owner get its own query string?

The owner can be also updated.

**Comment by josauder** [comment]
> > Do the visibility and endpointType parameters also apply to PUT /templates/{templateid} ?
> 
> yes
> 
> >    Or can one only update the template with all information in the body?
> 
> Yes.

What I mean is: when updating the template should these parameters be in the query or in the body?

**Comment by m1ci** [comment]
query

**Comment by ArneBinder** [comment]
> small correction, its type and not endpointType

@m1ci no, i've changed this for a better anderstanding of the parameter. For consistency reasons the serialization/deserialization of a template depends only on the Template model class in FREMEcommon and it's getter/setter methods from now on, the json is just forwarded by the Broker. So it's easy to change it back, if you prefere the old one (just rename the getter/setter of any parameter, but this needs a minor change in the database, so let me know if you do so). 

> query

No.
Somene moved the type parameter into the json body, what seemed to me as a good idea, so I also moved the visibility parameter. 

@josauder please consider this.

**Comment by m1ci** [comment]
@ArneBinder OK. Please next time in advance consult with me the changes concerning e-Link and e-Entity. Thanks.

**Comment by ArneBinder** [comment]
@m1ci you're right, please excuse this.

**Comment by jnehring** [comment]
I think it is a good idea to put all the data in the json and not some in the JSON and some in the query string. So lets leave the implementation in the broker as it is. But @m1ci  you are right we should discuss parameter changes before implementing them.

There is still an error in the JSON example. This will be covered by https://github.com/freme-project/e-Link/issues/60
