### ISSUE TITLE
Update logos on documentation homepage

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#116]
As written in email

**Comment by josauder** [comment]
> I have noticed partners’ logos are modified at http://api-dev.freme-project.eu/doc/ e.g. Agro-Know and Tilde. Could you please use original logos – see below, thank you in advance

What is exactly meant by modified?
The "original" logos simply look worse (lower resolution on Agroknow, more background in Tilde), see 

New:
![bad](https://cloud.githubusercontent.com/assets/12648328/10786436/6ce0d8b0-7d6a-11e5-8293-f1617339fa51.png)

Old:
![good](https://cloud.githubusercontent.com/assets/12648328/10786441/715fd184-7d6a-11e5-9c41-882e7ada4e3f.png)

Or is there some kind of copyright-metadata that was changed which I am unaware of?

I will push these now anyways.

**Comment by andish** [comment]
@josauder simply do not strecht the logos. fix one of dimension - width or height not both.
Original logo for Tilde is http://www.tilde.lv/sites/tilde.lv/files/logo_sources/tilde_logo.png
See the difference, on the right are the original logos:
![image](https://cloud.githubusercontent.com/assets/11315268/10787532/5668a1de-7d7a-11e5-82dd-b88148b4f331.png)

**Comment by jnehring** [comment]
You can use css properties max-width and max-height to scale the images without stretching them.
