### ISSUE TITLE
[pipelining] Documented response message not related to pipelines/templates/

### ISSUE THREAD

**Issue by andish** [freme-project/freme-project.github.io#118]
Response message with '404 not found' is not possible for this request.

**Implementation Notes** 
Returns all visible pipelining templates

it just returns emty array if no pipelene template available.

This possible message is releted for request with id
`GET /pipelining/templates/{id}`

**Comment by ghsnd** [comment]
This is correct.
Can the API documentation be updated for

```
GET /pipelining/templates/ 
```

Please remove the `404 Not found` response, as it is never returned.
