### ISSUE TITLE
Create user - no information about roles in response message

### ISSUE THREAD

**Issue by andish** [freme-project/freme-project.github.io#119]
As the response after successful creation returns a role for me, I want to know more about it.

```
{
  "name": "Andis",
  "role": "ROLE_USER"
}
```

**Comment by jnehring** [comment]
We could put some information about the role system in the documentation, in the [Authentication article](http://api-dev.freme-project.eu/doc/knowledge-base/authentication.html).

@andish does this solve the issue? Or where do you expect more information?

**Comment by andish** [comment]
Yes, it solves. Plus I would suggest linking to Authentication article from documentation of Create users under Implementation Notes.

**Comment by jnehring** [comment]
Ok. I move the issue to #123 and #124
