### ISSUE TITLE
Horizontal scrollbar at Simple and Full documentation pages

### ISSUE THREAD

**Issue by andish** [freme-project/freme-project.github.io#120]
Horizontal scroll-bar appears at screen resolution 1280x1024.
OS: Windows 10
Browser: Chrome

**Comment by jnehring** [comment]
@andish is the scroll bar unnecessary?

**Comment by andish** [comment]
yes, the body of page is to wide for header.
![image](https://cloud.githubusercontent.com/assets/11315268/10758210/91da4e56-7cb8-11e5-90eb-0ebb3e7ae1c3.png)

**Comment by jnehring** [comment]
@josauder can you reproduce this bug on a windows machine? And fix it?

**Comment by josauder** [comment]
I think I have fixed this. Works on win7 and chrome, IE10, MS Edge, and ubuntu+firefox.

**Comment by jnehring** [comment]
@andish please check if the bug is fixed.

**Comment by andish** [comment]
Yes, it looks great for me now. Thanks
