### ISSUE TITLE
Update API Doc informat and outformat

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#121]
Please update the possible values for informat and informat in these endpoints:

POST /e-entity/dbpedia-spotlight/documents
POST /e-entity/freme-ner/documents
POST /e-link/documents/
POST /e-terminology/tilde
POST /e-translation/tilde

These endpoints support these values for both informat and outformat:
- text/html
- text/xml
- application/x-xliff+xml
- application/x-openoffice

**Comment by josauder** [comment]
Should I also add the new formats to possible Content-Type/Accept headers?

**Comment by jnehring** [comment]
Yes please add the same information for Content-Type and Accept headers. Thanks for reminding me :-)
