### ISSUE TITLE
Full documentation page - unclear behavior of links for each e-service

### ISSUE THREAD

**Issue by andish** [freme-project/freme-project.github.io#122]
- Show/Hide - toggles visibility of e-service operations. This is clear
- List Operations - strange behaviour
  - if operations hidden, then shows it. Partly covers the first link.
  - if operations visible and also operation details expanded, then hide details
  - if operations visible and also operation details hidden, then do nothing
- Expand Operations - if operations visible and also operation details hidden, then expands details, othervise do nothing

I would suggest:
- Show/Hide operations
- Show/Hide operation details (visible if list of operations visible)

**Comment by jnehring** [comment]
My suggestion: Remove the buttons "Show/Hide", "List Operations", "Expand Operations". I think we do not need them and they confuse the user. @andish what do you think?

**Comment by andish** [comment]
fully agree. As now doc page have simple and full documentation, links no need more.

**Comment by jnehring** [comment]
@josauder please try to hide these three buttons on simple and full api documentation page using a css hack.
