### ISSUE TITLE
Update e-Link documentation

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#125]
1) The JSON example is invalid because it contains newline characters. @ArneBinder please update the example. Create a working JSON example with the SPARQL query in one line. Then add to the SPARQL query example a line saying "Please note that you have to convert newlines characters to \n before copy & pasting it in JSON".
2) Remove parameter "owner" from POST e-link/templates documentation
3) The formatting is wrong. There is an unncesessary gray box and the indent of the yellow box is not alligned
![image](https://cloud.githubusercontent.com/assets/10537540/10816216/707ef336-7e31-11e5-9ee7-aff840a84b96.png)

**Comment by ArneBinder** [comment]
implemented. @jnehring could you have a look?
I replaced the SPARQL query example by the one used in the JSON example, ok? The former was more minimalistic...

**Comment by jnehring** [comment]
Looks good. Thank you
