### ISSUE TITLE
Cannot remove auth token

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#126]
- I pasted an auth token in the API doc http://api-dev.freme-project.eu/doc/api-doc/full.html#/
- Then I did a call to POST /e-link/templates and created a template
- Then I removed the auth token from the input field
- Then I did a 2nd call to POST /e-link/templates

The 2nd call was still authenticated. It should be not authenticated because the token field is empty.

**Comment by josauder** [comment]
I will close this issue for now. When there is no X-Auth-Token set, swagger will send the header, but without any value set.

Otherwise we would have to overwrite part of the swagger code.

**Comment by andish** [comment]
I can't use e-tErminology and e-Translation via Full documentation.
@jnehring is anyone aware of changes auth header? Not handling the header with empty value or containing only one space?

Request:

```
curl -X POST --header "Content-Type: text/n3" --header "Accept: text/n3" --header "X-Auth-Token: " "http://api-dev.freme-project.eu/current/e-translation/tilde?input=hello&informat=turtle&outformat=turtle&source-lang=en&target-lang=de"
```

Response:

```
{
  "date": "Mon, 02 Nov 2015 14:56:22 GMT",
  "via": "1.1 QUIGON",
  "x-content-type-options": "nosniff",
  "access-control-max-age": "3600",
  "proxy-connection": "Keep-Alive",
  "connection": "Keep-Alive",
  "content-length": "0",
  "x-xss-protection": "1; mode=block",
  "pragma": "no-cache",
  "server": "Apache-Coyote/1.1",
  "x-frame-options": "DENY",
  "access-control-allow-methods": "POST, GET, OPTIONS, DELETE",
  "access-control-allow-origin": "*",
  "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
  "access-control-allow-headers": "x-requested-with, content-type",
  "expires": "0",
  "content-type": null
}
```

Actually there are two problems:
1) Incorrect error message (should be 401 not 406)
2) not accpting X-auth-token (documentation form adds single space)

**Comment by josauder** [comment]
@jnehring We might have to overwrite swagger code as I suggested

**Comment by josauder** [comment]
@andish Even when I remove the X-Auth-Token and try:

```
curl -X POST --header "Content-Type: text/n3" --header "Accept: text/n3"  "http://api-dev.freme-project.eu/current/e-translation/tilde?input=hello&informat=turtle&outformat=turtle&source-lang=en&target-lang=de"
```

I get 

```
{
  "exception": "eu.freme.broker.exception.BadRequestException",
  "path": "/e-translation/tilde",
  "message": "Error parsing NIF input",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1446480153561
}
```

This specific error seems unrelated to X-Auth-Token, as 

```
curl -X POST --header "Content-Type: text/n3" --header "Accept: text/n3" --header "X-Auth-Token: " "http://api-dev.freme-project.eu/current/e-translation/tilde?input=translate%20me&informat=text&outformat=turtle&source-lang=en&target-lang=de"
```

This call works.

**Comment by josauder** [comment]
I have implemented the overwritten function of swagger code in `_templates/swagger-doc.html`
It is also commented in the code but it basically prevents the setting of headers with the value `""`.

This should fix all API-Doc errors for now.
Previously to this workaround, it worked in firefox but did not work in chrome (not tested in other browsers).

**Comment by andish** [comment]
> @andish Even when I remove the X-Auth-Token and try:

sorry, my example contained wrong input type parameter value. 

But -  thanks, it works now.
