### ISSUE TITLE
API documentation lost text

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#129]
The current API documentation in FREME live looks like this
![image](https://cloud.githubusercontent.com/assets/10537540/10844464/18e1309c-7f00-11e5-8cd4-ee1cd508adb9.png)

Now on freme-dev it looks like this

![image](https://cloud.githubusercontent.com/assets/10537540/10844471/2a9e1354-7f00-11e5-8313-64677959681d.png)

Somehow we lost the text marked in red in the first screenshot. IMO we should put the text there. Is there a reason for this or is it a bug?

**Comment by josauder** [comment]
I think this is related to https://github.com/freme-project/Documentation/issues/120 , although all I did was change the width of the container. I will look into it.
