### ISSUE TITLE
Replace default value for page metadata "description"

### ISSUE THREAD

**Issue by andish** [freme-project/freme-project.github.io#131]
Before the release here should be placed appropriate value:
![image](https://cloud.githubusercontent.com/assets/11315268/10909788/15505bc8-8244-11e5-901b-58beb63de72f.png)

**Comment by jnehring** [comment]
Good point. Please use this text for description:

This site contains the documentation of the FREME project. The API documentation shows how to use FREMEs API. FREME showroom displays FREME in action. It contains demos, videos and other material to show what FREME can do. The tutorials section shows the capabilities of FREME and explains how to do certain things with the API. Knowledge Base contains a series of articles about FREME. Further there is page about License and Contact
