### ISSUE TITLE
I suggest to remove "Start" from main menu and make logo clickable

### ISSUE THREAD

**Issue by andish** [freme-project/freme-project.github.io#132]
It is a bit frustrating that the logo is not clickable and do not lead to the home of page.
And the term "Start" in not common in using for webpages and if the logo would be clickable than also useless. Or also could rename to "Home".

**Comment by jnehring** [comment]
I like both suggestions.

@josauder please make the logo to be a link to the homepage. And rename the "Start" menu point to "Home".
