### ISSUE TITLE
Inconsequence of parameter 'prefix' for enrichment methods

### ISSUE THREAD

**Issue by andish** [freme-project/freme-project.github.io#140]
For e-terminology prefix description is [this is wrong]:
![image](https://cloud.githubusercontent.com/assets/11315268/10997995/590f3f3e-849a-11e5-85e8-2a1722b4f420.png)

In e-translation:
![image](https://cloud.githubusercontent.com/assets/11315268/10998011/84581e90-849a-11e5-93fc-bb11779108bf.png)
Same for:
Post /e-entity/freme-ner/documents
POST /e-entity/dbpedia-spotlight/documents

But in e-Link and pipelening, where also is possible conversion from plaintext to NIF, such parameter not available.

**Comment by m1ci** [comment]
>  But in e-Link and pipelening, where also is possible conversion from plaintext to NIF, such parameter not available.

e-Link accepts/produces only NIF.

**Comment by andish** [comment]
Same for e-terminology and e-translation, but other formats are handled by broker.

E-Link documentation provides long list of possible in-formats:
![image](https://cloud.githubusercontent.com/assets/11315268/10998376/67290552-849d-11e5-9009-e1e28dd323f4.png)

**Comment by jnehring** [comment]
@andish What exactly is the problem? Can you suggest a better description?

**Comment by andish** [comment]
Parameter "prefix": used in conversion from plaintext to NIF and has same job for multiple endpoints.

Only correct description is in e-translation documentation (see 2nd picture in the 1st post), in others the parameter is missing or written as 'unused'  (see 1st picture in the 1st post) however it is not true - it is used.
