### ISSUE TITLE
Write article: "Security aware programming"

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#144]
This should cover how authorization works in FREME to assist developers in securing resources.

 It is part of knowledge base. Contents
- OwnedResource
- Links to Spring authentication / security voter
- Link to authentication article
- Example of AccessDecisionVoter

**Comment by ArneBinder** [comment]
TODO:
- finish article
- create ready-to-use example on github

**Comment by jnehring** [comment]
How about adding the example to one of the examples in https://github.com/freme-project/freme-examples ?

So you do not have to add all this stuff like maven pom.xml, spring configuration file, ...

**Comment by ArneBinder** [comment]
sounds good!

**Comment by jnehring** [comment]
Ok so when you have updated the example please add a section to the article "create e-service" or "create b-service" in https://github.com/freme-project/freme-parent/wiki that explains that these files belong to another article.

**Comment by jnehring** [comment]
[Extensive documentation of Spring Security](https://docs.spring.io/spring-security/site/docs/3.0.x/reference/springsecurity.html)

Please move the article to https://github.com/freme-project/freme-parent/wiki

**Comment by ArneBinder** [comment]
I've created an OwnedResource example. @jnehring could you give me write access to the freme-examples repo, please?

**Comment by jnehring** [comment]
I gave you write access to freme-examples repo

**Comment by jnehring** [comment]
Thanks, the article is looking good. I added one paragraph to first chapter "OwnedResource".

One question: Does the OwnedResource / OwnedResourceManagingController also provide a standard behaviour for create entity privilege? That means when using OwnedResourceManagingController can anonymous users create entities or only logged in users?

**Comment by ArneBinder** [comment]
> One question: Does the OwnedResource / OwnedResourceManagingController also provide a standard behaviour for create entity privilege? That means when using OwnedResourceManagingController can anonymous users create entities or only logged in users?

No, this isn't yet implemented. Should we do so? If yes, how should this be done exactly? Should we have a special "anonymous" user and authenticate as this silently if no authentication was done?

**Comment by jnehring** [comment]
With anonymous user I mean an API call that has no authentication attached to it. My question is: What happens if the anonymous user tries to create / update / delete a resource managed by OwnedResourceManagingController. Is the access allowed or denied?

**Comment by ArneBinder** [comment]
This is denied. See paragraph "Restricted endpoints" in the [authentication article](http://api-dev.freme-project.eu/doc/knowledge-base/authentication.html), it still holds for the new architecture.

**Comment by jnehring** [comment]
> This is denied. See paragraph "Restricted endpoints" in the authentication article, it still holds for the new architecture.

Ok. I added a bullet point the section owned resource to describe this.

I also changed the title of the article to "Implementing restricted access to database resources" because I think this is more clear.

Some more comments on the article:
- Please remove the section about jackson serialization. This belongs to another article "FREME persistence layer" so please save it somewhere for later.
- Please re-order the headings. There was a heading 1 that repeated the page title, which is not necessary. I removed this heading 1. Now all headings have too much indend.

> I've created an OwnedResource example

Please share the link to the codes.

**Comment by ArneBinder** [comment]
Thanks for the feedback, I will integrate this.

> >  I've created an OwnedResource example
> 
> Please share the link to the codes.

It is in the section "OwnedResource", the paragraph starting with **NOTE**. Should I put it somwhere else?

**Comment by jnehring** [comment]
> It is in the section "OwnedResource", the paragraph starting with NOTE. Should I put it somwhere else?

Oh I did not see this. Sorry. It is ok there.

Please add also the information somewhere in the article that ownedresources need to be in the package eu.freme.common.model. Same for repositories and so daos.

**Comment by ArneBinder** [comment]
> Please add also the information somewhere in the article that ownedresources need to be in the package eu.freme.common.model. Same for repositories and so daos.

The source code examples for the model, repository and the dao start with this line:
`// Ensure to use this package, otherwise your entities are not integrated into the database schema!` or
`// Ensure to use this package, otherwise the repository interface will not be scanned by Spring!`

Should I also add some words to the surrounding text?

**EDIT**: I've added some text (NOTEs). But not for the DAO, it do not have to be in the package.

**Comment by ArneBinder** [comment]
@jnehring I have finished your remarks. But what exactly do you mean with

>  I added a bullet point the section owned resource to describe this.

in https://github.com/freme-project/Documentation/issues/144#issuecomment-190230800?
