### ISSUE TITLE
Write knowledge base article about FREME NER

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#146]
It should cover how FREME NER works internally.

**Comment by m1ci** [comment]
first draft is available at: http://api-dev.freme-project.eu/doc/knowledge-base/freme-ner.html

**Comment by jnehring** [comment]
Thank you. @m1ci is this the final version? Can we close this issue?

**Comment by m1ci** [comment]
I will extend it with the requirements from https://github.com/freme-project/Documentation/issues/166

**Comment by m1ci** [comment]
the article has been extended with the requirements from https://github.com/freme-project/Documentation/issues/166

**Comment by jnehring** [comment]
Good work! Just one comment: I sometimes get questions why entities are not spottet in a text like "hello world abc berlin". Maybe you can add a paragraph to the tips section that explains that entity spotting and linking works best on clean text which means correct grammar, correct spelling (including capitalization), correct punctuation marks, ...

**Comment by m1ci** [comment]
> Good work! Just one comment: I sometimes get questions why entities are not spottet in a text like "hello world abc berlin". Maybe you can add a paragraph to the tips section that explains that entity spotting and linking works best on clean text which means correct grammar, correct spelling (including capitalization), correct punctuation marks, ...

Very valid comment! will definitely add that. Thanks.

**Comment by m1ci** [comment]
done. see Tips section.
https://github.com/freme-project/Documentation/blob/master/_pages/knowledge-base/freme-ner.md

**Comment by jnehring** [comment]
Thanks
