### ISSUE TITLE
Bugfix swagger.yaml

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#147]
Somebody reported an error that the swagger.yaml shows errors when being loaded in the online editor. Please try to reproduce and fix these errors.

**Comment by jnehring** [comment]
This seems to be more complicated then expected. We will do it later.

**Comment by fsasaki** [comment]
@jnehring , do we have a timeline for this? Could it be part of the 0.6 release?

**Comment by jnehring** [comment]
A bugfixed version was kindly provided by @davidwabnitz: https://github.com/davidwabnitz/FREME-Swagger

**Comment by ArneBinder** [comment]
swagger errors should be fixed. But could contain some layout issues (in examples etc).

**Comment by ArneBinder** [comment]
Fixed all layout issues in examples:
- post /e-entity/freme-ner/datasets (2)
- post /e-entity/freme-ner/documents
- post /e-link/documents/
- post /e-link/templates/
- post /e-publishing/html
- post /e-terminology/tilde
- post /e-translation/tilde
- post /pipelining/templates/
- post /pipelining/chain (3)
- get /user/{username}
- post /authenticate

Can we close this?

**Comment by jnehring** [comment]
Thank you. I will take a closer look at the changes before closing the issue
