### ISSUE TITLE
Write list of FREME features

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#149]
[In this GDoc](https://docs.google.com/document/d/1IVvtcZbb4Tdu4PK5iDmmNv2JNc8j2CzSXCypzxZ5uG4/edit#)

**Comment by jnehring** [comment]
Next steps
- Add links to tilde documentation for language pairs and domains for terminology and translation
- Compare the list of requirements from d1.1 with the updated requirements d2.2, d3.2, d4.2, d5.2
- Compare table 5 of d1.2 with updated requirements d2.2, d3.2, d4.2, d5.2

**Comment by ArneBinder** [comment]
1) the links are added
2) d2.2, d3.2, d4.2, d5.2 are integrated, as far as possible
3) table 5 of d1.2 is copied into the document and compared, as far as possible. But there are still some issues with this table (marked red, should also be corrected in the D1.2 document!).

@fsasaki: the correctness of 2) and 3) depends on the correct mapping from datasets to domains, see table "Implemented Datasets".

Furthermore, the column "datasets" is deleted from table "Features that are requirements in D1.1 but not implemented yet", see footnote.

**Comment by jnehring** [comment]
Thanks
