### ISSUE TITLE
Remove Content-Type header and Accept header from documentation

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#151]
We still support these parameters to stay NIF compatible. But they cause confusion so we should remove them. See discussion in #142 

We discuss this in the developers call before implementing it.

**Comment by josauder** [comment]
Any news on this issue?

**Comment by jnehring** [comment]
We will discuss this on next developers call on wednesday

**Comment by andish** [comment]
Writing tutorials I realized that documentation forms are indeed very confusing and not understandable for new visitors.
One thing is the input form and other the way how every e-service accepts parameters.
From users perspective, following form would be better:
![image](https://cloud.githubusercontent.com/assets/11315268/13353301/0fb933b2-dc9c-11e5-9049-fe6d23328894.png)
1. By removing some form elements, it do not means, that must remove informat/outformat/input query parameters. 
2. Below the form could generate both invoking variants and not mixing them. If use of query string parameters, then no http headers shown and vice versa. Two clean alternative examples how to use e-service.
3. As e-Services do not support GET requests, I don't see any benefit of having informat/outformat/input parameters.

**Comment by jnehring** [comment]
> Writing tutorials I realized that documentation forms are indeed very confusing and not understandable for new visitors.

I agree. We should invest some time in improving the design of the page. I created #192 to collect the ideas we had in this topic.

> As e-Services do not support GET requests, I don't see any benefit of having informat/outformat/input parameters.

I agree. This issue says we should drop the Content-Type and Accept headers, but I think it is better to drop informat and outformat too. Content-Type and Accept headers are standard in the HTTP world and since we build an HTTP API we should adopt to these standards.

**Comment by ArneBinder** [comment]
The parameter informat and outformat is removed from the api-doc. @jnehring Can we close this?
