### ISSUE TITLE
pipelining: enhance API documentation

### ISSUE THREAD

**Issue by ghsnd** [freme-project/freme-project.github.io#152]
Hi,

For the requests [/pipelining/chain/](http://api-dev.freme-project.eu/doc/api-doc/full.html#!/pipelining/post_pipelining_chain) and [/pipelining/chain/{id}](http://api-dev.freme-project.eu/doc/api-doc/full.html#!/pipelining/post_pipelining_chain_id) a new **optional** parameter has been added:

**parameter**: `stats`
**values:** `true` or `false`
**description:** if `true`: adds timing statistics to the response: total duration of the pipeline and duration of each service called in the pipeline, in milliseconds.
**parameter type:** path
**data type:** string

Example:

```
curl -X POST --header "Content-Type: text/plain" --header "Accept: application/json" -d "Brussels is the capital of Belgium." "http://api-dev.freme-project.eu/current/pipelining/chain/37?stats=true"
```

The response now contains a `metadata` part (timings) and a `content` part (original pipeline response).

**Comment by jnehring** [comment]
@ghsnd I assume the default value for stats is false?

**Comment by ghsnd** [comment]
Yes. Sorry I forgot to mention.
