### ISSUE TITLE
Formats of e-link/documents

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#153]
Please update the list of formats of POST e-link/documents endpoint.

informat, outformats:
json-ld
turtle
n3
n-triples
rdf-xml

Content-Type and Accept headers:
text/turtle (default)
application/ld+json
application/n-triples
application/rdf+xml
text/n3

Delete all the other formats.

**Comment by m1ci** [comment]
> json-ld, turtle, n3, n-triples, rdf-xml

These values are OK for the parameters but any of these are not valid values neither for the Content-Type nor the Accept header.

For the Content-Type and the Accept header we should use the corresponding mime type.

**Comment by jnehring** [comment]
Thanks milan I updated the list.

**Comment by ArneBinder** [comment]
> For the Content-Type and the Accept header we should use the corresponding mime type.

Especially, the mime type "application/json+ld" still does not exist, we should use "application/ld+json".

**Comment by m1ci** [comment]
> There is still no "application/json+ld", we should use
> "application/ld+json".

​`​
application/ld+json
​`​
​ is the only valid value.​

**Comment by jnehring** [comment]
I updated the list.
