### ISSUE TITLE
Knowledge base article about filter

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#155]
For the filters created in https://github.com/freme-project/Broker/issues/143 create a knowledge base article with sections
- Introduction / general explanation
- Example (call to e-Terminology -> NIF -> filter -> output)
- List of filters
- Explanation of management API

The article should cover "normal" select filters only and not SPARQL construct queries.

**Comment by ArneBinder** [comment]
Implemented, @jnehring could you have a look? 
Lacking a good e-Terminology example, there is just one using e-Entity.
The description of `terminology-terms-only` is still missing.

**Comment by jnehring** [comment]
Good work! Some comments:
- Please add to the section "Using filters" the original output of the API call in turtle and the output of the filter. In that way users can see what the filter does without executing the CURL request themselves.
- Please change the title to "Simply FREME output using SPARQL filters"
- In "Using filters", add a sentence: "To see a list of all publicly available SPARQL filters use the API endpoint http://api-dev.freme-project.eu/current/toolbox/filter/manage "

It is ok to have just an example for e-Entity in the documentation, no need for examples for all e-Services.

**Comment by ArneBinder** [comment]
Integrated comments. But 

> In "Using filters", add a sentence: "To see a list of all publicly available SPARQL filters use the API endpoint http://api-dev.freme-project.eu/current/toolbox/filter/manage "

was added to the "Available filters" section, because it is more related to this and it's immediate above the "Using filters" section. @jnehring: bad idea?

**Comment by jnehring** [comment]
> was added to the "Available filters" section, because it is more related to this and it's immediate above the "Using filters" section

perfect. your solution is better then the one i suggested. thanks.
