### ISSUE TITLE
Add filter endpoint to api documentation

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#156]
1. collect information about the new endpoints: 
   - filter management
   - filtering
2. add this to the swagger.yaml
3. add short description and link to knowledge base article about postprocessing

**Comment by ArneBinder** [comment]
Filter management endpoints:
- POST /toolbox/filter/manage/{filter-name}: Creates a new filter. The filter will be constructed from the body content, which has to be a valid SPARQL SELECT query as plain text. See the [Simplify FREME output using SPARQL filters](/knowledge-base/filtering.html) article for further information. Ensure, that a filter with the name `filter-name` does not already exist. Requires [authentication](knowledge-base/authentication.html).
  - visibility (optional): Sets the visibility of this restricted resource, see [authentication article](knowledge-base/authentication.html).
  - description (optional): Sets a description for this filter.
- PUT /toolbox/filter/manage/{filter-name}: Updates the filter with the name `filter-name`. Requires [authentication](knowledge-base/authentication.html). If you just want to transfer the ownership or change the visibility without updating the SPARQL filter query, send `EMPTY`, `NULL` or ` ` (a sting containing only whitespace) as body.
  - visibility (optional): Updates the visibility of this restricted resource, see [authentication article](knowledge-base/authentication.html). Defaults to `PUBLIC`.
  - description (optional): Updates the description of the filter.
  - newOwner (optional): Transfers ownership to another user. This has to be the name of an existing user.
- GET /toolbox/filter/manage/{filter-name}: Returns one specific filter with specified `filter-name` in JSON.
- GET /toolbox/filter/manage: Returns all read accessible filters, see [authentication article](knowledge-base/authentication.html) for further information.
- DELETE /toolbox/filter/manage/{filter-name}: Removes the filter with specified name. Requires [authentication](knowledge-base/authentication.html).

@jnehring should we have the filtering endpoint at the api doc respectively should this endpoint be accessible from outside of freme?

filter endpoint:
- POST /toolbox/filter/documents/{filterName}: This endpoint allows to execute a certain filter against a RDF graph sent as post body or as value of the NIF `input` parameter. For more information and a list of available filters, see the [Simply FREME output using SPARQL filters](knowledge-base/filtering.html) article.
  - input (optional): The RDF graph, which will be queried, in the specified RDF format. Overwrites the post body content.
  - informat (optional): Any NIF RDF format supported by FREME services: `turtle`, `json-ld`, `rdf-xml`, `n3`, `n-triples` (perhaps provide a common list?). Overwrites the `content-type` header value.
  - outformat (optional): `csv`, `json`, `xml` or any NIF RDF format supported by FREME services (perhaps provide a common list?). Overwrites the `accept` header value.

**Comment by jnehring** [comment]
> should we have the filtering endpoint at the api doc respectively should this endpoint be accessible from outside of freme

Yes it should be accessible from outside of FREME. Lets wait for the feedback from FREME developers before integrating this into the API documentation, maybe there will be a change.

**Comment by ArneBinder** [comment]
OK. But the filter management endpoints can be already added to the api doc? Or better waiting with this, too?

**Comment by jnehring** [comment]
Lets delay this issue completely until we have discussed it on the developers call.

**Comment by fsasaki** [comment]
It would be nice to have in 
http://api-dev.freme-project.eu/doc/knowledge-base/filtering.html
an example call of the filter mechanism with a pipeline. Is that feasable? Sorry if this is the wrong issue.

**Comment by fsasaki** [comment]
I am trying to run the example from the e-internationalisation tutorial, the e-terminology processing, with filtering. Without filtering this works

curl -X POST --header "Content-Type: text/html" --header "Accept: application/json+ld" -d @in-t.html "http://api-dev.freme-project.eu/current/e-terminology/tilde?source-lang=fr&target-lang=en&mode=full"

With filtering, e.g.
curl -X POST --header "Content-Type: text/html" --header "Accept: application/json+ld" -d @in-t.html "http://api-dev.freme-project.eu/current/e-terminology/tilde?source-lang=fr&target-lang=en&mode=full&filter=sourcelang-targetlang"

I don't get a response. If I set the accept header to application/json there is no response at all. @ArneBinder , can you give me a correct example how this work? See also the question for a different example here 
https://github.com/freme-project/Documentation/issues/156#issuecomment-171447574

**Comment by fsasaki** [comment]
adding @andish to the conversation, just in case this is an e-Terminology issue.

**Comment by ArneBinder** [comment]
@fsasaki could you provide the content of in-t.html so I can replicate the error exactly?
If you want to have a working example for the formats mentioned, outformat=json-ld works with the example from the knowledge base article. I still have to figure out, what's going wrong with the mime type versions.

**Comment by ArneBinder** [comment]
let's move this discussion concerning the bug to https://github.com/freme-project/Broker/issues/154

**Comment by ArneBinder** [comment]
@fsasaki sorry, #156 (comment) slipped my mind. What kind of example do you want to have? Could you provide a pipeline you want to have in this?

**Comment by fsasaki** [comment]
Hi Arne, attached is in-t.html (with txt extension to allow github upload). For the pipeline, it would  be nice to have an example with a pipeline consisting of e-entity and e-link.
[in-t.txt](https://github.com/freme-project/Documentation/files/107123/in-t.txt)

**Comment by jnehring** [comment]
@josauder please add these endpoints to the api documentation

**Comment by josauder** [comment]
I have added this to the [API Doc](http://api-dev.freme-project.eu/doc/api-doc/full.html).

I am not sure about the Http Status Codes. For example, POST /toolbox/filter/documents against a non-existing filter gives:

```
{
  "exception": "eu.freme.common.exception.FREMEHttpException",
  "path": "/toolbox/filter/documents/extract-entities-onlysdfdsf",
  "message": "Could not find filter with name='extract-entities-onlysdfdsf'",
  "error": "Internal Server Error",
  "status": 500,
  "timestamp": 1454343276423
}
```

Maybe another status code (404?) would be better?

When calling GET /toolbox/filter/manage/{nonexisting-filter-name}, I get 404 Status Code.

Also, when I call  POST /toolbox/filter/documents and use the `input` parameter instead of the post body, I get the following error:

```
{
  "exception": "org.springframework.http.converter.HttpMessageNotReadableException",
  "path": "/toolbox/filter/documents/extract-entities-only",
  "message": "Required request body content is missing: org.springframework.web.method.HandlerMethod$HandlerMethodParameter@44ea3182",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1454343636305
}
```

**Comment by ArneBinder** [comment]
@ArneBinder please fix `GET /toolbox/filter/manage` (falsely copied from `GET /toolbox/filter/manage/{name}`)

**Comment by jnehring** [comment]
> I have added this to the API Doc.

thank you

> I am not sure about the Http Status Codes. For example, POST /toolbox/filter/documents against a non-existing filter gives

I raised https://github.com/freme-project/Broker/issues/156 and https://github.com/freme-project/Broker/issues/157 to fix the status codes

> Also, when I call POST /toolbox/filter/documents and use the input parameter instead of the post body, I get the following error:

I think it is ok to require users to send the query via post body. There is no need to send this also via SPARQL query.

**Comment by ArneBinder** [comment]
All done.
