### ISSUE TITLE
Typo in filter documentation

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#159]
[Simplify FREME output using SPARQL filters](http://api-dev.freme-project.eu/doc/knowledge-base/filtering.html) might have a typo.

This query should return all named entities in the first sentence of the eiffel tower wikipedia article as CSV list:

```
entity
http://dbpedia.org/resource/Champ_de_Mars
http://dbpedia.org/resource/Torkham
http://dbpedia.org/resource/Eiffel_Tower
http://dbpedia.org/resource/France
http://dbpedia.org/resource/Paris
http://dbpedia.org/resource/Eiffel_(programming_language)
```

The first line of the example is "entity". Is this correct?

**Comment by ArneBinder** [comment]
Yes, this is correct, the first line is the header of the csv table.
I will change the description to: "...eiffel tower wikipedia article as CSV **table**:"

**Comment by jnehring** [comment]
Please add a sentence to the documentation to explain this.

**Comment by ArneBinder** [comment]
fixed.
