### ISSUE TITLE
dead link in http://api.freme-project.eu/doc/0.4/knowledge-base/starting-freme.html

### ISSUE THREAD

**Issue by fsasaki** [freme-project/freme-project.github.io#160]
The tutorial says
"You can download the distribution from http://api.freme-project.eu/freme-distributions"
but the link is not working.

**Comment by jnehring** [comment]
The link should point to http://api-dev.freme-project.eu/freme-distributions from both live and dev version of the homepage.

@josauder please update this.

**Comment by fsasaki** [comment]
the link at
http://api.freme-project.eu/doc/0.4/knowledge-base/starting-freme.html
is not updated yet, it still points to http://api.freme-project.eu/freme-distributions

**Comment by jnehring** [comment]
When I installed the new version of the API documentation during the release the link was fixed. But it is only plaintext and not a link. @josauder please make it a link that you can click.

**Comment by josauder** [comment]
This is now updated in the current Version of the project (api-dev).

**Comment by jnehring** [comment]
thank you
