### ISSUE TITLE
Double check list of demos / tutorials

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#162]
Please read through the list of tutorials and demos. Test if they work.

Then go through the [feature set of FREME](https://drive.google.com/file/d/0B647G8B_sNwkNVhRdDZFamJBRlk/view?usp=drive_web) and compile a list where additional tutorials are needed.

**Comment by ArneBinder** [comment]
FREME-Showroom:
- The page "Mockup a plugin for the CKEditor using FREME e-Services" is not listed at the "Overview" page **fixed**
- everything else works as expected

Tutorials:
- [Using the e-Entity & e-Link Pipeline](http://api-dev.freme-project.eu/doc/tutorials/pipeline-entity-link.html): OK
- [How to translate from English to Dutch with e-Translation and e-Terminology](http://api-dev.freme-project.eu/doc/tutorials/translate_EN-NL_including_terminology.html)
  - it is complicate to execute the given requests by my own - the code box is headlined "cURL", but I can not execute the first curl command neither from windows (cmd), nor does it work in a bash **fixed**. The second one works just from a bash.
- [Named Entity Recognition against Custom Dataset](http://api-dev.freme-project.eu/doc/tutorials/entity-recognition-against-custom-dataset.html): temporarily down (freme-ner)? can not execute anything. **EDIT:** something in the example calls seems to kill the service. **fixed**
- [Creating an EPUB using existing HTML content](http://api-dev.freme-project.eu/doc/tutorials/html-to-epub.html): example curl call works in a bash, but not from windows (see section: General)
- [How to write a tutorial](http://api-dev.freme-project.eu/doc/tutorials/how-to-write-tutorials.html): fixed
- [Create a new e-Service](http://api-dev.freme-project.eu/doc/tutorials/implement-eservice.html)
  - @jnehring is "line 46" in [this paragraph](https://github.com/freme-project/Documentation/blob/master/_pages/tutorials/implement-eservice.md#embedding-the-e-service-in-freme) correct?
- [Recognizing entities in XLIFF content](http://api-dev.freme-project.eu/doc/tutorials/spot-entities-in-xliff.html): fixed
- [Translate XLIFF 1.2 from English to French](http://api-dev.freme-project.eu/doc/tutorials/translate-xliff-FR-EN.html): 
  - try-it-out fails: 
    `{"readyState":4,"responseText":"{\n  \"exception\": \"eu.freme.broker.exception.ExternalServiceFailedException\",\n  \"path\": \"/e-translation/tilde\",\n  \"message\": \"External service failed with status code 404\",\n  \"error\": \"Not Found\",\n  \"status\": 404,\n  \"timestamp\": 1454604946127\n}","status":404,"statusText":"Not Found"}`
  - curl fails: `{
    "exception": "eu.freme.broker.exception.ExternalServiceFailedException",
    "path": "/e-translation/tilde",
    "message": "External service failed with status code 404",
    "error": "Not Found",
    "status": 404,
    "timestamp": 1454605199854
    }`
  - NOTE: tilde e-translation is not down, it works via the api doc

General: 
- To make cURL commands executable also from windows cmd, every curl parameter value has to be encapsulated in double quotation marks. Therefore embedded double quotation marks have to be escaped. New lines provide some problems, too. But adapting this destroys readability. And the escaped json is annoying when pasting into postman. @jnehring how should this be handled? Two boxes for every example? I think the best would be a button: "escape this and copy to clipboard", similar to the one known from github.com, if this would be feasible. Or giving up the windows curl support in examples?

PS: I added a javascript function to the code of [How to write a tutorial](http://api-dev.freme-project.eu/doc/tutorials/how-to-write-tutorials.html) and two buttons (commented out), which copy the content of a field to the clipboard. The code to escape the double quotation marks and the new lines still has to be added.

**Comment by fsasaki** [comment]
Thanks, @ArneBinder . I'd suggest that you put the tutorial owners into the loop and if that speeds things up just make the changes needed.

**Comment by ArneBinder** [comment]
@fsasaki good point. But at first I would like to collect all points to avoid unnecessary noise and exclude misunderstandings on my part.

> if that speeds things up just make the changes needed. 

of course.

**Comment by fsasaki** [comment]
Makes sense.

**Comment by ArneBinder** [comment]
**List of features without tutorial/showcase (feel free to withdraw any item if you think it is implemented after all):**
- General:
  - Basic user management  
- e-Entity:
  - Speeding up by using only a subset of the NER workflow (spotting, linking, classification)
  - Linking for a single entity (provided by the client as simple string) 
  - (REST endpoint to manage datasets) --> we should  wait until security is implemented
- e-Link
  - Enrich NIF content with predefined query templates (just implemted in the pipeline tutorial)
  - Built-in templates for common use cases
  - Secured REST endpoint to manage templates
  - Exploring a resource against a SPARQL or RDF endpoint  
  - FREME internal SPARQL and LDF server
- e-Terminology
  - NIF compatible 
  - Option to limit the service’s annotation to a certain Tilde collection
  - Optional domain specificity
- e-Translation
  - NIF compatible
  - ITS 2.0 category support
  - Optional domain specificity
  - Usage of different publicly available or private translation systems

**Comment by fsasaki** [comment]
Thank you for this, @ArneBinder . I'll put that on the agenda of tomorrow's plenary call.

**Comment by jnehring** [comment]
### comments on API testing

> How to translate from English to Dutch with e-Translation and e-Terminology

Please fix the 2nd CURL - I think it is not properly escaped.

> Translate XLIFF 1.2 from English to French:

Change target-language from french to german, in XLIFF example, CURL and Javascript

> To make cURL commands executable also from windows cmd

We do not support windows CURL.

**Comment by ArneBinder** [comment]
Implemented.

> > How to translate from English to Dutch with e-Translation and e-Terminology
> 
> Please fix the 2nd CURL - I think it is not properly escaped.

But now I get:

```
{
  "exception": "eu.freme.broker.exception.BadRequestException",
  "path": "/e-translation/tilde",
  "message": "Error parsing NIF input",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1455014299143
}
```

**Comment by jnehring** [comment]
Opened new issues for the undocumented features.
For the bug in e-translation curl I created #164
