### ISSUE TITLE
Write e-Entity documentation

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#166]
- Speeding up by using only a subset of the NER workflow (spotting, linking, classification)
- Linking for a single entity (provided by the client as simple string)
- (REST endpoint to manage datasets) --> we should wait until security is implemented

Related to #146

**Comment by m1ci** [comment]
The article http://api-dev.freme-project.eu/doc/knowledge-base/freme-ner.html has been extended with documentation of these three features.

**Comment by m1ci** [comment]
please check by tomorrow morning. By tomorrow EOB we want to have final version.

**Comment by jnehring** [comment]
Looks good.
