### ISSUE TITLE
Write e-Link documentation

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#167]
- Enrich NIF content with predefined query templates (just implemted in the pipeline tutorial)
- Built-in templates for common use cases
- Secured REST endpoint to manage templates
- Exploring a resource against a SPARQL or RDF endpoint
- FREME internal SPARQL and LDF server

**Comment by m1ci** [comment]
covered and documented all points.
However creation/updata/removal of a template is not working due to https://github.com/freme-project/e-Link/issues/67
@jnehring please check

**Comment by jnehring** [comment]
Nice work, thank you. two smaller comments.
- It might be useful to integrate a link to the [filtering article](http://api-dev.freme-project.eu/doc/knowledge-base/filtering.html) to the section "simplify output"
- Add a link to the [authentication article](http://api-dev.freme-project.eu/doc/knowledge-base/authentication.html) in the section to the "Paste your token." part of the create template section.

**Comment by m1ci** [comment]
done.

**Comment by jnehring** [comment]
Nice, thanks
