### ISSUE TITLE
life demos in freme documentation on 0.5 version do not work

### ISSUE THREAD

**Issue by fsasaki** [freme-project/freme-project.github.io#170]
see e.g.
http://api.freme-project.eu/doc/0.5/freme-showcase/ease-of-adaption.html
or
http://api.freme-project.eu/doc/0.5/tutorials/translate_EN-NL_including_terminology.html
the demo work in the dev version of the API. I wanted to demo these in Friday afternoon - it no fix by then is possible that's ok, I'll then use the dev version.

**Comment by jnehring** [comment]
The bug is fixed. I set the wrong API url in the configuration.
