### ISSUE TITLE
response content types lists contain content types not supported as response

### ISSUE THREAD

**Issue by fsasaki** [freme-project/freme-project.github.io#171]
e.g. for e-entity: x-openoffice. Appologies if this is covered by a different issue, in that case feel free to close this one.

**Comment by jnehring** [comment]
@ArneBinder please remove the x-openoffice from all "outformat" parameters and "accept" headers in the documentation for all api calls.

**Comment by ArneBinder** [comment]
fixed.

**Comment by fsasaki** [comment]
note that this issue was not only related to open office, see above "e.g. open office". One needs to go through the whole API documentation and check if the input and output types are right.
- Felix

**Comment by ArneBinder** [comment]
I checked (and fixed, except of the one below) all input/output types.
But what should we do with the endpoint `post /pipelining/chain/{id}`? At the moment this endpoint discards the informat/outformat and content-type/accept values. Just the request body of the request is put into the body of the first reqest of the pipeline. Is this good behaviour?

**Comment by jnehring** [comment]
Please document this behaviour in the implementation notes of the API endpoint. Then create a new issue that the Content-Type and Accept header should be removed from the documentation. Further link to the [pipelines tutorial](http://api-dev.freme-project.eu/doc/tutorials/pipeline-entity-link.html) from every pipelines API endpoints implementation notes.

**Comment by andish** [comment]
Best UX would be if changed pipelines structure. Remove any input/output format fields from the pipeline configuration, input/ouput formats should be specified by HTTP headers, and intermediate formats between e-services would be by default nif rdf/turtle (the users should not be care about it). This would be same behavior like for any other enrichment service.

**Comment by fsasaki** [comment]
+1 to Andis.

**Comment by jnehring** [comment]
Good idea Andis.

**Comment by ArneBinder** [comment]
@andish 's proposal is implemented. 
The possible values for content-type and accept headers for the /pipelining/chain/{id} endpoint are restricted to rdf formats and in addition to the formats accepted by e-internalisation for the input, so we allow only working combinations (at least for this endpoint).

But I'm still not sure about xml as input type. It seems to be possible for every e-service (via e-internalisation), isn't it? @jnehring But as a result of our last discussion we removed this. @fsasaki can you help here?

**Comment by fsasaki** [comment]
> But I'm still not sure about xml as input type. It seems to be possible for every e-service (via e-internalisation), isn't it?
> After chatting with Jan I don't think that XML is possible currently.

**Comment by ArneBinder** [comment]
@fsasaki @jnehring but [this](https://github.com/freme-project/basic-services/blob/master/internationalization/src/main/java/eu/freme/bservices/internationalization/okapi/nif/converter/NifConverter.java#L279) suggests the opposite. And when I enable [this test](https://github.com/freme-project/basic-services/blob/master/internationalization/src/test/java/eu/freme/bservices/internationalization/api/InternationalizationAPITest.java#L110-L132) at my local machine it runs without errors. The test uses [this xml file](https://github.com/freme-project/basic-services/blob/master/internationalization/src/test/resources/nifConversion/src1/test1.xml).

**Comment by fsasaki** [comment]
Well, then I would say: cool! And my bad, I was not aware of this. Then I'd propose that you add XML to the list.

**Comment by ArneBinder** [comment]
alright

**Comment by ArneBinder** [comment]
Added informat xml. Wait for https://github.com/freme-project/basic-services/issues/49.

**Comment by ArneBinder** [comment]
https://github.com/freme-project/basic-services/issues/49 revealed that internalisation roundtripping works fine with xml.

**Comment by jnehring** [comment]
@ArneBinder I think we never tried out XML workflows. Please try to process some XML documents as input documents. When we document it we at least have to try if it works.

**Comment by ArneBinder** [comment]
@jnehring I already tried [this file](https://github.com/freme-project/basic-services/blob/master/internationalization/src/test/resources/nifConversion/src1/test1.xml), it works. But we can check other xml files, if you want.

**Comment by ArneBinder** [comment]
@jnehring can we close this?
