### ISSUE TITLE
Update of demo in life version  in 0.5 version

### ISSUE THREAD

**Issue by fsasaki** [freme-project/freme-project.github.io#173]
I made a small fix to the xml to rdf demo
https://github.com/freme-project/Documentation/commit/8d56e365f595d215739a24fd9d9cbeff3e67c181
is it possible to include this in the 0.5 version? if not that is totally fine, just asking.

**Comment by jnehring** [comment]
done. @fsasaki please test if it works as expected.

**Comment by fsasaki** [comment]
works, thanks.
