### ISSUE TITLE
missing parameters (types, domain) documentation for e-entity

### ISSUE THREAD

**Issue by m1ci** [freme-project/freme-project.github.io#175]
I just noticed that the domain and types parameter is not documented for the e-entity.

These two parameters are briefly described in http://api.freme-project.eu/doc/0.5/knowledge-base/freme-ner.html
but here is some more info on that:

domain parameter: takes as input a domain ID, and it only returns entities from this domain. The domain IDs are from the TaaS domain classification system.
https://term.tilde.com/domains
Note that not all domains are supported in FREME NER - we need data for it. The domains we cover are the one that wripl considered as relevant for their use case.

How it works: For example, you can set domain=TaaS-2007 and in the results you will get entities only from the sports domain. Note, that the domain IDs are case sensitive.
Try this: http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?informat=text&input=Diego%20Maradona%20is%20from%20Argentina.&outformat=turtle&language=en&dataset=dbpedia&domain=TaaS-2007
... only Diego Maradona will be returned since only this entity is from the sports domain. Argentina is country.

types parameter: takes as input list of one or more entity types separated by a comma. The result is a list of extracted entities with these types.
Try this: http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents/?informat=text&input=Diego%20Maradona%20is%20from%20Argentina.&outformat=turtle&language=en&dataset=dbpedia&types=http%3A%2F%2Fdbpedia.org%2Fontology%2FCountry
... only the entity Argentina will be returned since is type of country.
Note that the types should be encoded.

**Comment by jnehring** [comment]
@ArneBinder please add two parameters to the swagger documentation of /e-entity/freme-ner/documents

domain parameter: Takes as input a domain ID, and it only returns entities from this domain. The domain IDs are from the TaaS domain classification system. More information about the domain parameter in [FREME NER documentation](http://api.freme-project.eu/doc/0.5/knowledge-base/freme-ner.html).

types parameter: Takes as input list of one or more entity types separated by a comma. The result is a list of extracted entities with these types. More information about the domain parameter in [FREME NER documentation](http://api.freme-project.eu/doc/0.5/knowledge-base/freme-ner.html).

**Comment by ArneBinder** [comment]
Added the two parameters to the doc.
@m1ci please check the documentation and close this issue if it is convient for you.

**Comment by m1ci** [comment]
in the types param description its not said that the types are ontology classes, and they should be encoded since they are send as part of the URL. I would suggest following description (changes are highlighted):

Takes as input list of one or more entity types separated by a comma. **The types are URLs of ontology classes and they should be encoded.** The result will*\* contain entities only of these types.*\* More information about the **types** parameter in FREME NER documentation.

for the domain parameter I suggest following description:

Takes as input a domain ID, and it only returns entities from this domain. The domain IDs are from the **[TaaS domain classification system](https://term.tilde.com/domains). For example, the sports domain is identified with the `TaaS-2007` ID. Note that the IDs are case-sensitive.** More information about the domain parameter in FREME NER documentation.

**Comment by ArneBinder** [comment]
Ok, thanks for the feedback. I will put this into the docu.

**Comment by ArneBinder** [comment]
fixed. Can we close this?

**Comment by m1ci** [comment]
the parameters are not documented in the "full API documentation" page
http://api-dev.freme-project.eu/doc/api-doc/full.html#!/e-Entity/execute

**Comment by ArneBinder** [comment]
I have assumed the parameters belong to [this endpoint](http://api-dev.freme-project.eu/doc/api-doc/full.html#!/e-Entity/execute_0). Should this be added to Spotlight, too? Or where do you want me to add this information?

**Comment by m1ci** [comment]
my mistake. they belong only to FREME NER.
sorry for the noise. The documentation is OK.
