### ISSUE TITLE
Create dataset fails

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#176]
When I want to create a dataset using the tutorial [Entity recognition against custom dataset](http://api.freme-project.eu/doc/0.5/tutorials/entity-recognition-against-custom-dataset.html) and I paste the example dataset in description then I get an error:

{"readyState":4,"responseText":"{\n  \"exception\": \"org.springframework.web.bind.MissingServletRequestParameterException\",\n  \"path\": \"/e-entity/freme-ner/datasets\",\n  \"message\": \"Required String parameter 'language' is not present\",\n  \"error\": \"Bad Request\",\n  \"status\": 400,\n  \"timestamp\": 1455273020492\n}","status":400,"statusText":"Bad Request"}

It works when I put another description, e.g. "hello world".

**Comment by m1ci** [comment]
the error says, Required String parameter 'language' is not present
Do you provide language param?

**Comment by m1ci** [comment]
does it work now?

**Comment by jnehring** [comment]
no

**Comment by m1ci** [comment]
it works to me.

**Comment by jnehring** [comment]
I will check it again next week.

**Comment by jnehring** [comment]
I investigated this further. This cURL

```
curl -X post -d @data.txt "http://api-dev.freme-project.eu/current/e-entity/freme-ner/datasets?informat=n-triples&name=jan-test&description=xx"
```

with [data.txt](https://github.com/freme-project/Documentation/files/132267/data.txt) produces

```
{
  "exception": "org.springframework.web.bind.MissingServletRequestParameterException",
  "path": "/e-entity/freme-ner/datasets",
  "message": "Required String parameter 'language' is not present",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1455618258840
}
```

The [documentation](http://api-dev.freme-project.eu/doc/api-doc/full.html#!/e-Entity/createDataset) does not specify language as required parameter.

**Comment by m1ci** [comment]
fixed, dont forget to set your content type header.

**Comment by jnehring** [comment]
thanks
