### ISSUE TITLE
Create dataset tutorial fails

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#177]
When I create a dataset in the tutorial [Named entity recognition against custom dataset](http://api-dev.freme-project.eu/doc/tutorials/entity-recognition-against-custom-dataset.html) on freme-dev then I get this error. On freme-live it works:

{"readyState":4,"responseText":"{\n  \"exception\": \"org.springframework.web.bind.MissingServletRequestParameterException\",\n  \"path\": \"/e-entity/freme-ner/datasets\",\n  \"message\": \"Required String parameter 'language' is not present\",\n  \"error\": \"Bad Request\",\n  \"status\": 400,\n  \"timestamp\": 1455273020492\n}","status":400,"statusText":"Bad Request"}

Maybe this is related to #176

**Comment by m1ci** [comment]
the error says: Required String parameter 'language' is not present

do yo provide language parameter?

**Comment by jnehring** [comment]
In the tutorial I cannot provide a language parameter. Further the [documentation](http://api.freme-project.eu/doc/0.5/api-doc/full.html#!/e-Entity/createDataset) says that the parameter is optional.

**Comment by jnehring** [comment]
Sorry I pasted the wrong error message (the one from #176). The error here is

{"readyState":4,"responseText":"{\n  \"exception\": \"eu.freme.broker.exception.BadRequestException\",\n  \"path\": \"/e-entity/freme-ner/datasets\",\n  \"message\": \"404 Not Found\",\n  \"error\": \"Bad Request\",\n  \"status\": 400,\n  \"timestamp\": 1455273458212\n}","status":400,"statusText":"Bad Request"}

**Comment by m1ci** [comment]
can you please share full URL along with the data? Thanks.

**Comment by jnehring** [comment]
It is a tutorial so full URLs and so on are under the surface. To reproduce the error you open the web page and fill out the form in step 2:
- dataset content: copy & paste the example dataset
- dataset serialization format: leave default value "n-triples"
- dataset-name: "jan-test"
- dataset description: "bla bla"

Then click "Submit the dataset!"

**Comment by m1ci** [comment]
Just check and the error is in the Broker - no request arrive to FREME NER.

**Comment by jnehring** [comment]
solved through https://github.com/freme-project/Broker/issues/163
