### ISSUE TITLE
Invalid NIF example e-Translation

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/freme-project.github.io#178]
The example of e-Translation contains syntax errors:
- It ends with  semicolon not period.
- URI's of prefixes contains whitespaces. (URI is all between < and >)

**Comment by andish** [comment]
Invalid example both in simple and full documentation:
http://api-dev.freme-project.eu/doc/api-doc/full.html#!/e-Translation/tildeTranslate
and
http://api-dev.freme-project.eu/doc/api-doc/simple.html#!/e-Translation/tildeTranslate

**Comment by jnehring** [comment]
@ArneBinder please correct the example and update the documentation.

**Comment by ArneBinder** [comment]
fixed.

**Comment by jnehring** [comment]
@pheyvaer please verify that it is ok now and then close the issue.
