### ISSUE TITLE
Add SPARQL filter example to e-Entity tutorial 

### ISSUE THREAD

**Issue by m1ci** [freme-project/freme-project.github.io#180]
the tutorial has been extended. See http://api-dev.freme-project.eu/doc/tutorials/entity-recognition-against-custom-dataset.html#step-4-simplify-the-results @jnehring is this enough? Please let us know by tomorrow morning. By tomorrow EOB we would like to have the final version of the tutorial. Thanks.

**Comment by jnehring** [comment]
well done. thank you
