### ISSUE TITLE
empty prefix declarations

### ISSUE THREAD

**Issue by fsasaki** [freme-project/freme-project.github.io#182]
swagger generates empty turtle prefix generations. I tried this with the example turtle input for the calls for e-entity, e-link and e-terminology. The generated CURL request starts in the data provided via -d like this

@prefix itsrdf:  .
@prefix xsd:  .

**Comment by jnehring** [comment]
Seems to be a bug in swagger. I raised https://github.com/swagger-api/swagger-ui/issues/1978

**Comment by andish** [comment]
Maybe then this section must remove at next release while not resolved. Better is no information than wrong information.

**Comment by fsasaki** [comment]
+1 to @andish . @jnehring , please consider removing the part that Andish mentioned if no fix is available.

**Comment by jnehring** [comment]
The problem has been fixed by swagger: https://github.com/swagger-api/swagger-ui/issues/1978 but we need to update when we want to use this.

**Comment by ArneBinder** [comment]
This works since the recompile of the swagger-ui. Using the newest swagger-client mentioned [here: swagger-api/swagger-ui#1978 ](https://github.com/swagger-api/swagger-ui/issues/1978) destroys it again.

**Comment by ArneBinder** [comment]
Can we close this?

**Comment by fsasaki** [comment]
From my side: yes
