### ISSUE TITLE
[Review] Getting started with e-Link

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/freme-project.github.io#184]
Introduction
- 'what is a template' --> 'what a template is'

Prerequisites
- 'what is a template' --> 'what a template is'

What is a template?
- 'Bellow' --> 'Below'

Step 3: Manipulation with templates
- 'manipulate with the templates' --> 'manipulate the templates'

Remove a template
- 'A template can be also removed.' --> 'A template can also be removed.'

FREME SPARQL and Linked Data Fragments endpoints
- 'The main lainging page' --> 'The main landing page'

**Comment by m1ci** [comment]
thanks, fixed

**Comment by m1ci** [comment]
no more comments, closing the issue
