### ISSUE TITLE
[Review] Named Entity Recognition against Custom Dataset

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/freme-project.github.io#185]
### Step 2: Submit the custom dataset to the e-Entity service

I get the following error when trying the example.

```
{"readyState":4,"responseText":"{\n  \"exception\": \"eu.freme.broker.exception.BadRequestException\",\n  \"path\": \"/e-entity/freme-ner/datasets\",\n  \"message\": \"409 Conflict\",\n  \"error\": \"Bad Request\",\n  \"status\": 400,\n  \"timestamp\": 1456388305314\n}","status":400,"statusText":"Bad Request"}
```

Unable to test the (most of) the other steps due to this.

**Comment by m1ci** [comment]
You tried to create dataset with name, which is already used - there exist dataset with name mydataset.
409 Conflict -> dataset with same name exist.

**Comment by pheyvaer** [comment]
OK, could you add the warning (in the text) for the user to create a dataset with a unique name. Because now I assume if I run the example that it should work if I don't change anything.

**Comment by pheyvaer** [comment]
Additionally, the next step gvies me the following error (the dataset was added using a unique name in the previous step):

```
{"readyState":4,"responseText":"{\n  \"exception\": \"eu.freme.broker.exception.BadRequestException\",\n  \"path\": \"/e-entity/freme-ner/documents\",\n  \"message\": \"Unsupported language.\",\n  \"error\": \"Bad Request\",\n  \"status\": 400,\n  \"timestamp\": 1456389321407\n}","status":400,"statusText":"Bad Request"}
```

**Comment by m1ci** [comment]
> OK, could you add the warning for the user to create a dataset with a unique name. Because now I assume if I run the example that it should work if I don't change anything.

Working on that.

> Additionally, the next step gvies me the following error (the dataset was added using a unique name in the previous step):
> 
> {"readyState":4,"responseText":"{\n  \"exception\": \"eu.freme.broker.exception.BadRequestException\",\n  \"path\": \"/e-entity/freme-ner/documents\",\n  \"message\": \"Unsupported language.\",\n  \"error\": \"Bad Request\",\n  \"status\": 400,\n  \"timestamp\": 1456389321407\n}","status":400,"statusText":"Bad Request"}

Fixed. Please check.

**Comment by pheyvaer** [comment]
Step 3 is working now.

**Comment by m1ci** [comment]
> OK, could you add the warning for the user to create a dataset with a unique name. Because now I assume if I run the example that it should work if I don't change anything.

Fixed, please check. Now the error is 

```
{
  "readyState": 4,
  "responseText": "{\n  \"exception\": \"eu.freme.broker.exception.BadRequestException\",\n  \"path\": \"/e-entity/freme-ner/datasets\",\n  \"message\": \"Dataset with this name already existis and it cannot be created.\",\n  \"error\": \"Bad Request\",\n  \"status\": 400,\n  \"timestamp\": 1456394805849\n}",
  "status": 400,
  "statusText": "Bad Request"
}
```
