### ISSUE TITLE
[Review] How to translate from English to Dutch with e-Translation and e-Terminology

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/freme-project.github.io#187]
### Introduction
- 'to improve or adjust translation senses': I don't really understand what is meant here.
-  'helps machine translation use them' --> 'helps machine translation to use them'
### Step 1 - using e-Terminology
- 'Annotate terms within the source text' --> 'Annotate terms within the source text.'
- The term ranks of the example don't match the output given by the service.
### Step 2: using e-Translation to translate
- A ':' is used in the title instead of a '-' as in the first step.
- 'The input data is the output of Step 1 - response of e-Terminology' --> remove ' - response of e-Terminology'
- Can you give the option to copy the cUrl command to the clipboard and that everything is on a single line. At the moment, the enters give problems in Terminal.
### Query e-services with single API call
- '<>Instead of querying... ' --> remove '<>'
- 'use pipelines' --> 'use a pipeline'

**Comment by andish** [comment]
Thanks, for comments. 

> Can you give the option to copy the cUrl command to the clipboard and that everything is on a single line. At the moment, the enters give problems in Terminal.

As I not linux user, I don't use Curl. Curl command is copied from Postman. Seems that this command is to long for terminal. So I am considering to remove all curl commands from our articles and provide HTTP examples. Like this:

```
POST /current/e-translation/tilde?source-lang=en&target-lang=de&key=u-iuo-2323-444-223-ABC HTTP/1.1
Host: api-dev.freme-project.eu
Accept: application/rdf+xml
Content-Type: text/plain

The EU in brief. The EU is a unique economic and political partnership between 28 European countries that together cover much of the continent.
```

**Comment by m1ci** [comment]
> So I am considering to remove all curl commands from our articles and provide HTTP examples.

there might be problems with long curl commands, but IMO curl is the fastest and most efficient way of sharing workable HTTP requests in a copy-paste fashion. Yes, postman is also very good option, however it takes some time to define the request. One more drawback is that postman examples can not be shared (correct me if I am wrong).

**Comment by andish** [comment]
>  but IMO curl is the fastest and most efficient way of sharing workable HTTP requests in a copy-paste fashion

True, but for Linux users

> postman examples can not be shared 

Also true, there are some serialization possibilities, but this will be postman as product specific

**Comment by m1ci** [comment]
It should be also possible to run cURL under Windows. See https://curl.haxx.se/download.html (search for Win32/64). Our students have been using https://www.cygwin.com/ which simulates Linux/UNIX/BSD environment and no problems so far.
Just a recommendation, in case you would like to run cURL under Windows. (sorry for the noise to the issue).

**Comment by andish** [comment]
Thanks @m1ci . For testing I am using Vagrant and via ssh to linux I can execute such command. But terminal do not accept such long commands and I do not have experience to solve such things. I could post a file from filesytem, but for demo curl command this is not reasonable.

But speaking about the goal of the tutorials - such Curl-only-examples discriminates non-linux users. At least I will provide HTTP example alongside Curl command.

**Comment by pheyvaer** [comment]
I was more hinting at something like this https://clipboardjs.com/
So the doc stays as it is. However, via a copy/paste button, the command is reformatted making it suitable for Terminal.

**Comment by andish** [comment]
This is good suggestion. But this should be integrated in top level of documentation page and used common approach across all tutorials.

**Comment by pheyvaer** [comment]
@andish of course :)

**Comment by andish** [comment]
But this do not solve the 2nd Curl sample. There is already an issue about that #164 
Command seems to large, because e-terminology returns a lot of data in first step.

So, what do you think, is the following approach reasonable for demo curl comand?
Curl:

```
curl -X POST -d "response-of-step1.ttl" "http://api-dev.freme-project.eu/current/e-translation/tilde?informat=json-ld&outformat=json-ld&source-lang=en&target-lang=nl";
```

where  the file **response-of-step1.ttl** is the response of e-Terminology.

**Comment by jnehring** [comment]
> I was more hinting at something like this https://clipboardjs.com/
> used common approach across all tutorials

Thats a good idea. But it is a lot of work also.

> So I am considering to remove all curl commands from our articles and provide HTTP examples.

Right now we use CURL in FREME as a standard. We use it in GitHub issues and also in the documentation. It is more work to generate a cURL request, especially for windows users, but is really useful for people who want to execute the command. I can understand that generating CURL commands is annoying but IMO we should have a common look and feel across FREME.

One tip: To quickly execute a curl request in windows I use the [Git Bash](https://git-for-windows.github.io/). It is a small lightweight linux shell for windows. It starts much quicker then a vagrant box and is therefore less annoying.

> So, what do you think, is the following approach reasonable for demo curl comand?

good solution.

**Comment by andish** [comment]
OK, I will shorten curl command to file name and implement suggestions. Also this article today will be a little bit extended according #169 . Working on that.

**Comment by andish** [comment]
The article has been updated.
Added new section Customising e-Translation:
http://api-dev.freme-project.eu/doc/tutorials/translate_EN-NL_including_terminology.html#customising

**Comment by pheyvaer** [comment]
'there is more' --> 'there are more'
small typo in the new section

**Comment by andish** [comment]
thanks, fixed.
