### ISSUE TITLE
[Review] [Knowledge Base] e-Internationalization

### ISSUE THREAD

**Issue by andish** [freme-project/freme-project.github.io#188]
1. Correct use of "e-Internationali**z**ation". In DoA and deliverables there is used a form of e-Internationali**s**ation. Should be consistent use.
2. "Wit this new functionality" --> "With this new functionality"
3. "a HTML file" -->  "an HTML file"
4. use of "he" :) should be used any form of "it",  "s/he" or "he or she". Multiple occurrences: "he doesn’t have", "he should be aware"
5. use of "itsrdf" in regular text without any clarification. itsrdf is nor standard nor abbreviation. It is commonly used technical prefix in RDF for namespace http://www.w3.org/2005/11/its/rdf describing ITS 2.0 / RDF Ontology.

**Round-tripping: how does it work?**
6. Hard to understand this sentence: "When converting a HTML file to NIF a second NIF file is produced, containing a context that also includes markups." First was original "HTML" or something else? Maybe better say first that "In HTML to NIF conversion two NIF files are created.... ".
7. "Anyway it is not relevant for new lines don’t affect the HTML file appearance in the browser." Something missing in the middle of sentence?
8. Not clear about ODT files - do it support ITS categories?

**Comment by jnehring** [comment]
@andish valid comments! thank you.

@ArneBinder please update the article

> 1. Not clear about ODT files - do it support ITS categories?

good question. unfortunately i cannot answer this. I raised https://github.com/freme-project/e-Internationalization/issues/36

**Comment by ArneBinder** [comment]
finished points 2 to 7.

**Comment by ArneBinder** [comment]
finished points 2 to 7.

**Comment by ArneBinder** [comment]
finished point 1.
@jnehring can we close this?

**Comment by jnehring** [comment]
thank you
