### ISSUE TITLE
[Review][Knowledge Base] Maintaining the Documentation Project

### ISSUE THREAD

**Issue by andish** [freme-project/freme-project.github.io#189]
Article looks very laconic and clear. 
Totally unfamiliar with technologies mentioned, but some comments:
1. "If it doesn’t work the first time go for: sudo apt-get install ruby-dev". Strange reason for installing a library. Does it helps always?
2. "Migrating Swagger-UI versions". Why should migrate something? if the server is already migrated, than this is obsolete section?
3. Tutorials are very different on content and targeted users. Maybe grouping would be good improvement for "Knowlegdebase" dropdown: 
-  Use of e-services
-  Maintain/set-up the FREME server

**Comment by jnehring** [comment]
Thank you for the suggestions.

> If it doesn’t work the first time go for: sudo apt-get install ruby-dev

Changed formulation 

> Tutorials are very different on content and targeted users. Maybe grouping would be good improvement for "Knowlegdebase" dropdown

Such grouping exists in the [Overview](http://api-dev.freme-project.eu/doc/knowledge-base/overview.html). But it should be updated, so I created #197)
