### ISSUE TITLE
[Review][Tutorial] Creating an EPUB using existing HTML content

### ISSUE THREAD

**Issue by andish** [freme-project/freme-project.github.io#191]
All is clear, some minor comments:
1. Link "e-Publishing Documentation" would scroll to the e-Publishing documentation http://api-dev.freme-project.eu/doc/api-doc/full.html#!/e-Publishing/htmlToEPub
2. "aformentioned articles, and their necessary files" --> "afor**e**mentioned articles and their necessary files."
3. Not mentioned in the article which version of EPUB format the service will create.

**Comment by pheyvaer** [comment]
Thanks Andis.
I addressed your comments. However, for some reason the URL you provide for comment 1 doesn't seem to make a difference. Does this work in your browser?

EDIT: OK, it works in Chrome, but not in Firefox.
