### ISSUE TITLE
Write tutorial: How to access FREME using various programming languages

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#193]
Take [this examples](https://www.w3.org/community/ld4lt/wiki/File:Freme-webinar-20160222-examples.zip). You can load the postman collection into postman and generate code snippets in curl, PHP V1 and Javascript jQuery AJAX. The article should have all 9 examples and each example has this form:
# example1: Example API Call

This example shows how to call FREME NER.
## Example in curl

...
## Example in Javascript / jQuery

...
## Example in PHP

...

Please change the calls in postman a bit:
- Remove the auth token (if possible)
- Please use only Content-Type and Accept header. Remove informat and outformat

**Comment by ArneBinder** [comment]
Implemented, see [here](http://api-dev.freme-project.eu/doc/tutorials/use-various-programming-languages.html).
@jnehring the URLs in example 4 are still hardcoded to freme-dev (it uses a filter which is not contained in freme 0.5) like in the postman collection.

**Comment by fsasaki** [comment]
Thanks, Arne. Small comment: the Cache-Control header is maybe not needed? Also, maybe add a link from "DKT" to
http://digitale-kuratierung.de/

**Comment by ArneBinder** [comment]
- added filter "place-and-lat-long" to freme live
- switched to dynamic URLs for example 4
- removed the Cache-Control header in all examples
- added DKT link

@fsasaki anything else missing? Or do you have other hints? If not, please close this issue.

**Comment by fsasaki** [comment]
Thanks, @ArneBinder . A very small item could you add after
"This tutorial shows some examples how to use FREME features in cURL, Javascript / jQuery or PHP V1."
A sentence like
"Please read the tutorial with the FREME 2016 February Webinar slides available at
https://www.w3.org/community/ld4lt/wiki/File:Freme-webinar-20160222-slides.pdf"
with a link to the slides. 
Feel free to then close the issue.

**Comment by jnehring** [comment]
To avoid the URL in the text I changed the sentence:

Please read the tutorial with the [FREME 2016 February Webinar slides](https://www.w3.org/community/ld4lt/wiki/File:Freme-webinar-20160222-slides.pdf).

And added it to the article.
