### ISSUE TITLE
[Knowledge Base][Authentication] update changed URLs

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#194]
When switching to the new architecture, some endpoints to manage OwnedResources change.
## Restricted endpoints

Some FREME endpoints are only accessible as authenticated user. At the moment these are:
- POST, PUT and DELETE **`/e-link/templates/{templateID}`** (template handling that needs write access)
  --> **`/e-link/manage/{templateID}`**
- POST, PUT and DELETE `/toolbox/filter/manage/{filterName}` (filter handling that needs write access)
- POST, PUT and DELETE **`/pipelining/templates/{pipelineID}`** (pipeline handling that needs write access)
  --> **`/pipelining/manage/{pipelineID}`**

...

The result of the resource managament endpoints:
- GET **`/e-link/templates`** --> **`/e-link/manage`**
- GET `/toolbox/filter/manage`
- GET **`/piepelining/templates`** --> **`/piepelining/manage`**

**Comment by jnehring** [comment]
This will be fixed by freme-project/basic-services#31
