### ISSUE TITLE
[API doc] adapt changed URLs to handle OwnedResources

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#195]
When switching to the new architecture, some endpoints to manage OwnedResources change.
- POST, PUT and DELETE **`/e-link/templates/[{templateID}]`** (template handling that needs write access)
  --> **`/e-link/manage/[{templateID}]`**
- POST, PUT and DELETE **`/pipelining/templates/[{pipelineID}]`** (pipeline handling that needs write access)
  --> **`/pipelining/manage/[{pipelineID}]`**
- GET **`/e-link/templates`** --> **`/e-link/manage`**
- GET **`/piepelining/templates`** --> **`/piepelining/manage`**

**Comment by jnehring** [comment]
@ArneBinder this is outdated and can be closed, right?

**Comment by ArneBinder** [comment]
Yes.
