### ISSUE TITLE
Move articles

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#198]
Please move the articles from https://github.com/freme-project/freme-parent/wiki to the API documentation homepage to knowledge base.

In the overview, put these articles into section "Knowledge base for FREME developers":

Overview on the FREME architecture
Creating a basic service
Setup FREME in the IDE
How to write an e-Service
Implementing restricted access to database resources

Do not move this article: Migrating an e-Service to the new architecture

Put this article in the "Knowledge base for FREME system administrators" section: Creating and running a FREME package

**Comment by jnehring** [comment]
The image is not correct: http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-developers/overview-of-the-freme-architecture.html

**Comment by josauder** [comment]
Oh i must have missed this. Fixed now
