### ISSUE TITLE
Add FREME NER documentation

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#202]
Extend [this article](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/freme-ner.html#) with information about FREME NER
- How to install (we can provide a first draft. The section about how to install the solr server needs to be written be @m1ci )
- Configuration options
- freme ner repo and freme-ner package
- add a table of contents

**Comment by jnehring** [comment]
Please add sections
- Table of contents
- How to install FREME NER"
  - Dependencies: EUse information from #219. Reference to the pre-requisites from http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/creating-and-running-a-freme-package.html
  - Information about maven dependency and spring configuration
- Configuration options: First 5 lines of https://github.com/freme-project/freme-ner/blob/master/src/test/resources/application.properties
- FREME NER on GitHub: Explain freme-ner e-service and freme-ner-dev package

**Comment by ArneBinder** [comment]
I have created the branch `freme-ner`, @jnehring please have a look at the `knowledge-base/freme-for-api-users/freme-ner.md`.

There is a lot of differently complicated content now, perhaps we move it to `freme-for-sysadmins`?

**Comment by jnehring** [comment]
Nice updates, thank you! Please merge it into the master and delete the branch.

> There is a lot of differently complicated content now, perhaps we move it to freme-for-sysadmins?

Please link to the article from both "freme for users" and "freme for sysadmins".  O think it is a good idea to have only one article about FREME NER.

**Comment by jnehring** [comment]
Please try to add the article to both sections using a dummy page that does a redirect. When this is too complicated dont invest too much time and leave the article in freme for users only.

**Comment by ArneBinder** [comment]
implemented.
