### ISSUE TITLE
Update readmes

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#203]
The Readme files on GitHub should be updated.
- Broker, e-Link, e-Entity, e-Publishing, e-Internationalisation (others?) get a note "deprecated" and the new location of the codes should be stated.
- basic-services, e-services, freme-packages repo need readme files

**Comment by jnehring** [comment]
I added the deprecated notes to the readme files of the deprecated repositories.

**Comment by jnehring** [comment]
Structure
- Heading
- Text what this repository is about
- Links
  - FREME project homepage
  - FREME documentation homepage
  - https://github.com/freme-project
  - Maybe links to the documentation that are useful for this particular repository
- License

**Comment by ArneBinder** [comment]
Implemented. @jnehring please have a look.

**Comment by jnehring** [comment]
looks good, thank you!
