### ISSUE TITLE
[kb for sysadmins: basic-services] Add documentation for basic services

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#204]
To this page: http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/basic-services.html

Please try to use the same structure as the proxy filter documentation. You should only write a short description for each service and link to other documentation pages when possible.

Document these basic services:
- logging-filter
- rate-limiter
- internationalization-filter
- pipelines

**Comment by ArneBinder** [comment]
Add missing b-services:  
  <li><a href="#internalisation-filter">Internalisation Filter</a></li>
  <li><a href="#logging-filter">Logging Filter</a></li>
  <li><a href="#internalization">Internalisation</a></li>
  <li><a href="#nif-converter">NIF Converter</a></li>
  <li><a href="#sparql-converters-controller">SPARQL Converters</a></li>
  <li><a href="#users-controller">Users Controller</a></li>
  <li><a href="#users-controller">XSLT Converter</a></li>

**Comment by ArneBinder** [comment]
implemented.
