### ISSUE TITLE
[kb for sysadmins] Write list of e-Services 

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#208]
Similar to [List of basic services](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/basic-services.html)

**Comment by ArneBinder** [comment]
@jnehring please have a look to http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/e-services.html

**Comment by jnehring** [comment]
Thank you this is a great start. I will take over from here.

**Comment by jnehring** [comment]
I added some information to the article. This issue is finished.
