### ISSUE TITLE
Create database initialisation scripts

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#209]
Create two database initialisation scripts.
- init-templates.sql initialises the [templates](http://api-dev.freme-project.eu/doc/api-doc/list-templates.html) 
- init-filters.sql initialises the filters.

The owner of these things is user "admin".

Then create a new article "Initialising FREME" with two short paragraphs about these two files. The article should also have a link to [FREME configuration options](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/configuration-options.html) on how to create the admin user by configuration.

**Comment by ArneBinder** [comment]
> ```
> init-templates.sql initialises the templates
> init-filters.sql initialises the filters.
> ```

Should this add the current content of the dev database?

[Here](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/initialising-freme.html) is a first draft of the page. I'm not sure about what to add.

**Comment by ArneBinder** [comment]
> Should this add the current content of the dev database?

The filter script adds all filters from dev (except `jan-test`), the template script all from [the template list](http://api-dev.freme-project.eu/doc/api-doc/list-templates.html), ok?

**Comment by jnehring** [comment]
Good start!
- Please add an introduction sentence like "This article explains how to initialise the FREME database."
- Please test if the property [hibernate.hbm2ddl.import_files](http://docs.jboss.org/hibernate/orm/4.1/manual/en-US/html_single/#configuration-misc-properties) can be used to auto import these init skripts, e.g. for initialising the H2 in memory database. If it works, refer to this option in the article.
- In the SQL commands, Remove the create table / drop table stuff. Just the INSERT INTO commands are enough.
- In the SQL commands, Please remove also the id field from the INSERT TABLE statements. The ID is auto generated by the table schema.
- In the SQL commands, please remove all comments also.

**Comment by ArneBinder** [comment]
TODO:

> Please test if the property hibernate.hbm2ddl.import_files can be used to auto import these init skripts, e.g. for initialising the H2 in memory database. If it works, refer to this option in the article.

**Comment by ArneBinder** [comment]
Added a paragraph concerning hibernate autoload data (hibernate.hbm2ddl.import_files), but could not test it yet without my IDE.

**Comment by jnehring** [comment]
I tested it and the feature works now also without IDE. Just one last thing: Please remove the LOCK TABLES / UNLOCK TABLES statements from the three files because they cause problems with the H2 database. Then close the issue,

**Comment by ArneBinder** [comment]
implemented.
