### ISSUE TITLE
Add filter endpoint to tutorial

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#210]
Please add a paragraph about endpoint [/toolbox/convert/documents/{name}](http://api-dev.freme-project.eu/doc/api-doc/full.html#!/Toolbox/post_toolbox_convert_documents_name) to the [filter tutorial](http://api.freme-project.eu/doc/0.5/knowledge-base/filtering.html).

**Comment by ArneBinder** [comment]
Implemented.
