### ISSUE TITLE
Few comments on the NIF converter documentation

### ISSUE THREAD

**Issue by m1ci** [freme-project/freme-project.github.io#211]
- In the “Implementation Notes” specify what concrete formats can be converted - what is behind “any format supported by e-Internalisation”?
- Nowhere to specify the Accept header in the client in the documentation
- “Parameter content type” - its not parameter but header
- “Response Content Type” - I recommend something more understandable like “Response format (Accept header)”

**Comment by jnehring** [comment]
> In the “Implementation Notes” specify what concrete formats can be converted - what is behind “any format supported by e-Internalisation”?

People can click the link or open the dropdowns "response content type" or "parameter content type" to see the formats. I think this is enough.

> Nowhere to specify the Accept header in the client in the documentation
> “Parameter content type” - its not parameter but header
> “Response Content Type” - I recommend something more understandable like “Response format (Accept header)”

Response Content Type is the accept header. You are right this is not a good caption. I opened #212 for this.
