### ISSUE TITLE
XML demo does not work

### ISSUE THREAD

**Issue by fsasaki** [freme-project/freme-project.github.io#213]
See attached screenshot. The error is produced by calling e-Entity.

<img width="640" alt="freme_documentation_-_from_xml_to_rdf_step_by_step" src="https://cloud.githubusercontent.com/assets/1177858/14778512/a7b3e3c8-0ad3-11e6-9d2d-e37a8096bec9.png">

**Comment by jnehring** [comment]
There was a problem with the broker (https://github.com/freme-project/FREMECommon/issues/22). I restarted the broker and now it works fine.

Please check again and close the issue if it is solved.

**Comment by fsasaki** [comment]
Works fine, thanks!
