### ISSUE TITLE
Public version contains links to dev environment - curl samples in  FREME Enrichment Templates

### ISSUE THREAD

**Issue by andish** [freme-project/freme-project.github.io#215]
Section: FREME Enrichment Templates
http://api.freme-project.eu/doc/0.6/api-doc/list-templates.html

All templates contains curl examples to development server:
![image](https://cloud.githubusercontent.com/assets/11315268/14953290/0e1d57e6-1071-11e6-8b46-cdde56197c76.png)

**Comment by jnehring** [comment]
In the live version we should point only to the live api. When we work over the API documentation then we do a full text search on the live documentation to ensure this.

**Comment by ArneBinder** [comment]
This is fixed. But the two postman collections still contain api-dev mentions. @fsasaki should I change these, too?

**Comment by fsasaki** [comment]
Thanks, Arne. Yes, please change the postman collections.

**Comment by ArneBinder** [comment]
Fixed.
