### ISSUE TITLE
URL of public service is service specific not permanent

### ISSUE THREAD

**Issue by andish** [freme-project/freme-project.github.io#216]
URL is:
http://api.freme-project.eu/doc/0.6/api-doc/full.html,
but should be:
http://api.freme-project.eu/doc/current/api-doc/full.html

Steps to reproduce:
1) From http://www.freme-project.eu/  navigate to http://api.freme-project.eu/doc/current/
2) Menu contains version specific URLs like http://api.freme-project.eu/doc/0.6/api-doc/simple.html

**Comment by jnehring** [comment]
You are right. I will fix this.

**Comment by jnehring** [comment]
This will be fixed through #214. These links will all be the same then:
- http://api.freme-project.eu/doc/0.6/api-doc/full.html
- http://api.freme-project.eu/doc/0.5/api-doc/full.html,
- http://api.freme-project.eu/doc/current/api-doc/full.html,

**Comment by jnehring** [comment]
This will be fixed through #214. These three links will direct to the same page after #214 
* http://api.freme-project.eu/doc/0.6/api-doc/full.html
* http://api.freme-project.eu/doc/0.5/api-doc/full.html
* http://api.freme-project.eu/doc/current/api-doc/full.html
