### ISSUE TITLE
[Public FREME] Full and Simple API documentation omits Uris from preview

### ISSUE THREAD

**Issue by andish** [freme-project/freme-project.github.io#217]
Steps to reproduce:
1) select any enrichment e-service in simple or full API documentation
2) Copy example of NIF and paste it into 'body' field, 
3) Press Try it out
4) Curl section not showing any URI:
![image](https://cloud.githubusercontent.com/assets/11315268/14979160/33498694-1129-11e6-9ccd-4b1be0e76a5b.png)

**Comment by jnehring** [comment]
dublicate of #182
