### ISSUE TITLE
FREME NER installation instructions

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#219]
Please help us create installation instructions for FREME NER. DFKI can write the article. But we need help in these topics, you can put the text in this github issue.
- How to install and setup the Solr server
- How to install and setup the triple store
- How to create the domain.csv file
- Question: Why do we need the triple store anyways?

This issues solves a part of #202.

**Comment by m1ci** [comment]
> How to install and setup the Solr server

Here are instructions how to install Solr
http://lucene.apache.org/solr/quickstart.html
For Solr you will also need the schema.
which you can find at
http://rv2622.1blu.de/solrdev/#/elinker/files?file=schema.xml

> How to install and setup the triple store

to instal 7.20 follow
http://serverfault.com/questions/631673/virtuoso-opensource-7-1-how-do-i-build-an-ubuntu-deb-package-from-github-sourc

echo "deb http://packages.comsode.eu/debian wheezy main" > /etc/apt/sources.list.d/odn.list
wget -O - http://packages.comsode.eu/key/odn.gpg.key | apt-key add -
apt-get update
apt-get install -y virtuoso-opensource=7.2

After installation the web admin interface is at
http://localhost:8890/conductor
and the SPARQL endpoint at
http://localhost:8890/sparql

> How to create the domain.csv file

Its simple CSV file, here is the current one
https://github.com/freme-project/freme-ner/blob/master/src/main/resources/domains.csv
The first column is the domain name, the following are entity types that belong to this domain.

> Question: Why do we need the triple store anyways?

Domain specific NER, filtering entities by types, entity types, ...

**Comment by jnehring** [comment]
thank you.
