### ISSUE TITLE
[Freme Live] Workflow editor has strange output for HTML markup

### ISSUE THREAD

**Issue by andish** [freme-project/freme-project.github.io#220]
Steps to reproduce:
1. http://api.freme-project.eu/freme-workflow-editor/
2. Input text block --> Use Example: HTML5 --> Load
3. Add e-service-block --> press "e-entity"-->leave default values--> press 'enrich'

Result contains parts of NIF.
Possibly related to https://github.com/freme-project/e-Internationalization/issues/37

**Comment by jnehring** [comment]
I fixed freme-project/e-Internationalization#37 on freme-dev but I cannot test if it fixed this bug because of https://github.com/freme-project/freme-workflow-editor/issues/22

We can wait until the next release / mini release. Then we test again if this issue is solved.

**Comment by jnehring** [comment]
This bug came from the bug in the backend: https://github.com/freme-project/e-Internationalization/issues/37

The bug in the backend is fixed so now this works also.
