### ISSUE TITLE
Test interactive documentation

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#221]
Please test the interactive parts of the documentation:
- API documentation (simple and full)
- FREME showroom
- Tutorials

Create GitHub issues in this repository for all problems.

**Comment by fsasaki** [comment]
This should include as much as possible also fixing the issues. Also, for my usage (knowing at a conference what is working or not) I need a separate list of what is not working, i.e. a list I can use without having to browser github.

**Comment by jnehring** [comment]
Create dataset tutorial does not work: #218

**Comment by jnehring** [comment]
finished. thanks @bgrusdt . the buglist is located here: https://docs.google.com/document/d/13-uhaVC1Dpd9X7Cg2okPjRUMRWDDXyN10e2PAADrfQs/edit
