### ISSUE TITLE
extended API GET info about datasets - parameter type?

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#223]
In the full API documentation, the API call 
GET /e-entity/freme-ner/datasets/{name} returns a MalformedURLException
when asking for information about the datasets I get from GET /e-entity/freme-ner/dataset, e.g. name=dbpedia.

How am I supposed to specify the parameter correctly?

**Comment by m1ci** [comment]
try this
http://api-dev.freme-project.eu/current/e-entity/freme-ner/datasets/dbpedia?outformat=json

**Comment by m1ci** [comment]
the name of the dataset is part of the URI, not query param

**Comment by m1ci** [comment]
the name parameter is used only when you want to create dataset and assign it a name

**Comment by jnehring** [comment]
Right now this does not work on freme-live. On freme-dev we have already fixed the bug. I will install the latest version of FREME tomorrow on freme-live because we did a lot of bugfixes in the last week.

**Comment by jnehring** [comment]
fixed through https://github.com/freme-project/technical-discussion/issues/118
