### ISSUE TITLE
deletion of created dataset fails - extended-API documentation

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#225]
I'm trying to delete my previously created dataset which results in an InternalServerError because of a MalformedUrlException.

curl -X DELETE --header "Accept: application/json" --header "X-Auth-Token: f9ee068e-b304-499e-a43f-64fac36bb96e" "http://api.freme-project.eu/0.6/e-entity/freme-ner/datasets/testSetbrgru"

**Comment by jnehring** [comment]
Thanks for the bugreport. This is already fixed in the dev API. I will install the latest version on freme live and hopefully this bug will be tomorrow. I leave this issue open as a reminder to test it on live after the release.

**Comment by jnehring** [comment]
fixed through https://github.com/freme-project/technical-discussion/issues/118
