### ISSUE TITLE
update existing dataset fails - extended API 

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#226]
When  I try to update my existing dataset with one of the provided example datasets,  I get exit status code 406 and the response body says ' no content'.  

curl -X PUT --header "Content-Type: text/turtle" --header "Accept: text/n3" --header "X-Auth-Token: f9ee068e-b304-499e-a43f-64fac36bb96e" -d "  \"101 Communications, LLC\" .
" "http://api.freme-project.eu/0.6/e-entity/freme-ner/datasets/testSetbrgru?informat=turtle&language=en&visibility=public"

**Comment by m1ci** [comment]
what is the purpose of  -d " \"101 Communications, LLC\"  ?
what do you want to update?

**Comment by bgrusdt** [comment]
Thank you for your response. 
As I understood it in the extended api (PUT /e-entity/freme-ner/datasets/{name})
, I can update an existing dataset with new data  
when I specify the data to be added in the body and the dataset to be updated of course. 

 I intended to add the following  to my dataset (testSetbrgru):   http://www.lib.ncsu.edu/ld/onld/00000326 http://www.w3.org/2004/02/skos/core#altLabel "101 Communications, LLC" .

Did I get something completely wrong ?  I'm sorry, I'm new to this.

**Comment by m1ci** [comment]
maybe the API doc is misleading, but PUT can be used to **update metadata** about the dataset (description, owner, visibility,...), and **append triples** to the dataset.
Also, http://www.lib.ncsu.edu/ld/onld/00000326 http://www.w3.org/2004/02/skos/core#altLabel "101 Communications, LLC" is invalid triple, You need < and > signs at the begining and end of the subject and predicate.

**Comment by bgrusdt** [comment]
Thank you very much. 
I do have the <> <> around the subject and predicate. Apparently, they were  not copied correctly here, sorry for this.
I'm still not sure about this. What do I have to do differently to add the triple to the dataset then?

**Comment by m1ci** [comment]
Try smth like:
PUT at http://api-dev.freme-project.eu/current/e-entity/freme-ner/datasets/loc-authors?informat=n-triples&language=en&properties=http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23prefLabel%2Chttp%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2Ftitle

where the body of he request are the triples you want to add

and the headers
'X-Auth-Token': 'your token',
'Content-Type': 'text/n3'

**Comment by jnehring** [comment]
fixed through https://github.com/freme-project/technical-discussion/issues/118
