### ISSUE TITLE
simple-api link to tutorial section not working

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#227]
In the simple API
http://api.freme-project.eu/doc/0.6/api-doc/simple.html
the link (http://api.freme-project.eu/doc/0.6/Tutorials/overview.html) to the tutorial section does not work . (Not Found Error)

**Comment by jnehring** [comment]
@bgrusdt please update the link

**Comment by bgrusdt** [comment]
the link is updated.
