### ISSUE TITLE
persist parameter for creating new pipelining templates

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#228]
In the extended API
POST /pipelining/templates/  has the parameter 'persist'. The explanation in the documentation states that it still needs to be implemented. 
Does this still need to be done or is the documentation just not up to date?

**Comment by jnehring** [comment]
Upon each start up of FREME I get the message "Deleting pipelines that are older then one week". I think that means that the code that deletes old pipelines is executed, therefore I guess the "persist" parameter is implemented?

**Comment by ghsnd** [comment]
It is implemented indeed. If `persist = true`, then the pipeline will live "forever". If `false`, it will only live for a week. So the documentation should be updated.

**Comment by jnehring** [comment]
@bgrusdt please add the parameter to the documentation.

**Comment by bgrusdt** [comment]
fixed.
