### ISSUE TITLE
tutorials  - recognizing entities in XLIFF documents does not work

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#230]
In the tutorial section / Recognizing entities in XLIFF content, I get the following response when running it with the provided examples and default parameters.

{"readyState":4,"responseText":"{\"timestamp\":1463663898835,\"status\":500,\"error\":\"Internal Server Error\",\"exception\":\"eu.freme.common.exception.InternalServerErrorException\",\"message\":\"Conversion from \\"application/x-xliff+xml\\" to NIF failed\",\"path\":\"/e-entity/freme-ner/documents\"}","status":500,"statusText":"Internal Server Error"}

**Comment by jnehring** [comment]
The first example does not work on live, but it works on dev - I assume it will work after the release on live also.

The second example ("simplify output") fails on dev.

**Comment by jnehring** [comment]
The bug in this issue is fixed. But the tutorial still has problems due to https://github.com/freme-project/basic-services/issues/47
