### ISSUE TITLE
tutorials - acess FREME with various progr. languages Example 2 broken

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#231]
In Example 2 (Chaining of e-services client side) the provided curl statement seems to be invalid.

**Comment by jnehring** [comment]
I can confirm that the curl does not work. Please replace it with a single line curl and put the data in a file, like `curl -X POST -data @data.txt...-`. Please add the file to the documentation and link to it from the documentation.

**Comment by jnehring** [comment]
fixed
