### ISSUE TITLE
broken link in Showroom/ from xml to RDF

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#233]
The link on the following site 
http://api.freme-project.eu/doc/0.6/freme-showcase/xml-to-rdf.html

to the FREME API Documentation is not working.

**Comment by jnehring** [comment]
@bgrusdt when you find the time please fix the link. Please use a relative link (no absolute link) so it will work from both live and dev version.

**Comment by ArneBinder** [comment]
This is fixed in the dev version, so it will go to live with the next release.
