### ISSUE TITLE
invalid curl command in Tutorials access FREME with various programing languages  

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#236]
In this tutorial section
http://api.freme-project.eu/doc/current/tutorials/use-various-programming-languages.html#example-7

the curl commands of Example 7 and Example 8 result in the following error:
bash: !DOCTYPE: event not found

I suppose this has to do with the  opening and ending  ' and ".

**Comment by jnehring** [comment]
@bgrusdt please update the examples.

**Comment by bgrusdt** [comment]
The examples are updated.
