### ISSUE TITLE
[workflow editor] E-Entity does not work

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#238]
After adding the e-Entity e-Service and clicking on enrich, nothing happens. The console says:

```
ReferenceError: xmlToRdf is not defined
processXmlResponse()
 freme-workflow.js:211
eEntity.doEnrichment/<.success()
 e-services.js:31
n.Callbacks/i()
 jquery.min.js:2
n.Callbacks/j.fireWith()
 jquery.min.js:2
z()
 jquery.min.js:4
.send/c/<()
 jquery.min.js:4
```

**Comment by fsasaki** [comment]
I am getting now the error message below.

>  timestamp :1464153975862
> status :502
> error : Bad Gateway
> exception : eu.freme.bservices.filter.proxy.exception.BadGatewayException
> message : Proxy failed: java.net.SocketException: Zu viele offene Dateien
> path : /e-entity/freme-ner/documents

**Comment by jnehring** [comment]
The bug with "too many open files" originates here: https://github.com/freme-project/FREMECommon/issues/22

I restarted FREME, now it works.

**Comment by ArneBinder** [comment]
This is fixed.
