### ISSUE TITLE
[how-to-write-an-eservice] add description of SerializationFormatMapper 

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#239]
If any informat/outformat or Content-Type/Accept value other than the ones already registered via FREMECommon (plaintext, json, rdf types, see [here](https://github.com/freme-project/FREMECommon/blob/master/src/main/java/eu/freme/common/conversion/SerializationFormatMapper.java#L26-L49)), they have to be added to the SerializationFormatMapper. Otherwise internationalization-filter will report something similar to:

```
  "exception": "eu.freme.common.exception.BadRequestException",
  "path": "/e-publishing/html",
  "message": "Unsupported informat='multipart/form-data'.
```

Example format registration in the controller, e.g:

``` java
@Autowired
SerializationFormatMapper serializationFormatMapper;

@PostConstruct
public void init(){
     // This is the mandatory registration
     serializationFormatMapper.put("multipart/form-data", "multipart/form-data");
     // optional: mapping of a hand-defined type to the correct MimeType. If it is not an existing mimeType, this works just for the parameter "input"
     serializationFormatMapper.put("zip", "multipart/form-data");
 }
```

**Comment by jnehring** [comment]
Please put this in "how to write a basic service". E-Services usually follow the NIF conventions therefore do not accept other data formats.

**Comment by ArneBinder** [comment]
implemented.
