### ISSUE TITLE
[api-doc] remove "Response Class (Status 200)" and "Response Messages"

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#241]

**Comment by bgrusdt** [comment]
I have removed  Response Class (200) and ResponseMessages. By removing the entire 'responses:' block for each API Call also the field Response Content Type with its Drop-down menu was removed. This list of possible response types should still be included somewhere.

**Comment by ArneBinder** [comment]
This should be fixed by modifying and recompiling swagger-ui.js.

**Comment by ArneBinder** [comment]
I modified swagger-ui.js so that response classes and messages are not displayed. It does not matter if they are defined in the swagger.yaml.

Along the way I checked the swagger.yaml in the [online swagger editor](http://editor.swagger.io) which reveals several errors. I think we should continue to follow the swagger api specification to avoid parsing errors. @bgrusdt please check the errors with the [online swagger editor](http://editor.swagger.io). It seems that every [operation object](http://swagger.io/specification/#operationObject) has to contain at least one [response object](http://swagger.io/specification/#responsesObject).

**Comment by bgrusdt** [comment]
I added one response object (success) for each call. All errors are removed now.
