### ISSUE TITLE
[knowledgeBase-for API users]  missing body in example call

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#243]
The POST example in curl  in **How to attach an access token to an API call** does not secify a body  which I suppose is the reason the command results in an error:

```
curl -X POST --header "X-Auth-Token: f81ccf99-1d01-4e79-9a0b-8dfe84d8303c" "http://api-dev.freme-project.eu/current/e-link/templates?outformat=turtle&informat=json"
```

with token replaced by mine.

**Comment by jnehring** [comment]
Please change the API call
- To something that works, e.g. a call to FREME NER. It should be a call that does enrichment, so you can add to the documentation that this call can be used to access a private dataset. You do not need to create a private dataset, just use DBPedia.
- Change the URL from freme-dev to freme-live

**Comment by bgrusdt** [comment]
I have updated the example to 

```
 curl -X POST --header "Content-Type: text/plain" --header "Accept: text/n3" --header "X-Auth-Token: YOUR_TOKEN" "http://api.freme-project.eu/current/e-entity/freme-ner/documents?input=Welcome%20to%20Berlin%2C%20the%20capital%20of%20Germany.&language=en&dataset=dbpedia&mode=all"
```
