### ISSUE TITLE
[full-API e-link/template]  json example newlines

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#244]
In the full API Documentation,
in the json input example for POST/e-link/templates, the newlines must be still removed in order for the Call to work properly. 

```
 {
    "query": "PREFIX dbpedia: <http://dbpedia.org/resource/> \n PREFIX dbpedia-owl: <http://dbpedia.org/ontology/> \n PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> \n PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#> \n CONSTRUCT \n { \n ?museum <http://xmlns.com/foaf/0.1/based_near> <@@@entity_uri@@@> . \n } \n WHERE \n { \n <@@@entity_uri@@@> geo:geometry ?citygeo . \n ?museum rdf:type <http://schema.org/Museum> . \n ?museum geo:geometry ?museumgeo . \n FILTER (<bif:st_intersects>(?museumgeo, ?citygeo, 10)) \n } \n LIMIT 10",
    "endpoint": "http://dbpedia.org/sparql/",
    "label": "template title",
    "description": "template description",
    "endpointType": "sparql",
    "visibility": "public"
    }
```

works for me. I suppose this won't look nice though,  I will test it locally and update it if its okay. Otherwise we could use a uploaded file?

**Comment by jnehring** [comment]
The text says "Please note that you have to convert newline characters to \n before copy & pasting it in JSON:" so I think removing newlines is explained here.
I think we can close this issue or what do you think?

**Comment by ArneBinder** [comment]
I think we should provide working json, so we should put the query really in one line. A readable version is directly below.

**Comment by jnehring** [comment]
Please change the JSON example and remove newlines.

**Comment by bgrusdt** [comment]
I have updated the example.
