### ISSUE TITLE
[full-API e-link/templates] curl-example doesnt refer to this call

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#245]
In the full api under POST e-link/templates, the following example does not seem to be at the right place here. It refers to e-link/documents and includes localhost which is probably not on purpose?

```
  curl -v -d @example.ttl -X POST -H "Content-Type: text/turtle" "http://localhost:8080/e-link/documents?templateid=116&my_limit=5"
```

**Comment by jnehring** [comment]
please change this to "http://api.freme-project.eu/current/..."

**Comment by ArneBinder** [comment]
Perhaps we should provide the template 116 (it uses the user paremter `my_limit`) which is used in this example call.

**Comment by ArneBinder** [comment]
I added a modified version of template 1 with a parameterized LIMIT (via `@@@my_limit@@@`). It has the id 116. But this works for some values of my_limit only, moved to [this issue](https://github.com/freme-project/e-services/issues/15).
