### ISSUE TITLE
[delete user]  cannot delete user

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#246]
When I try to delete my newly created user, I get the following exception. 

```
{"timestamp":1464861231308,"status":500,"error":"Internal Server Error","exception":"org.springframework.dao.DataIntegrityViolationException","message":"could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement","path":"/user/testUserBG"}
```

I am not sure , but I thought, it had been working before..

**Comment by jnehring** [comment]
@ArneBinder please find out what is wrong here.

**Comment by ArneBinder** [comment]
I can not reproduce this bug.

**Comment by bgrusdt** [comment]
So we have figured out that the user could not be deleted because it was owner of some templates. How should this be handled?

**Comment by jnehring** [comment]
Once we had an on-delete event that deleted all templates (and datasets, tokens, ...) when the user was deleted. So I guess this stopped to work.

I move the issue to https://github.com/freme-project/FREMECommon/issues/23
