### ISSUE TITLE
[e-internationalisation] from html input to xml output 

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#247]
```
curl -X POST -d @docTest.html --header "Content-Type: text/html"  "http://api-dev.freme-project.eu/current/e-terminology/tilde?outformat=xml&source-lang=en&target-lang=it&mode=full&filter=terminology-terms-only"
```

This curl command which is provided in the Documentation Knowledge Base / FREME for api-users / e-internationalisation to explain the detection of terms in a html document results in the following exception.

```
{
  "exception": "eu.freme.common.exception.BadRequestException",
  "path": "/e-terminology/tilde",
  "message": "Can only convert to outformat \"text/xml\" when informat is also \"text/xml\"",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1464869984284
}
```

This combination is not supposed to work I think, but then, I am wondering where the xml comes from and what shall be changed in the example, input or output format?

**Comment by bgrusdt** [comment]
The same problem appears in pipeline examples in Knowledge Base / FREME for API-Users / **Simplify FREME output using SPARQL filters**

**Comment by jnehring** [comment]
The CURL command is wrong. When informat=text/html then outformat needs to be text/html also. Roundtripping only works when informat=outformat. Please change the CURL command.

> The same problem appears in pipeline examples in Knowledge Base / FREME for API-Users / Simplify FREME output using SPARQL filters

Can you please point out which CURL does not work?
I tried several CURL requests from this tutorial and they did not work.

**Comment by bgrusdt** [comment]
This was caused by not checking in the internalization filter if the postprocessing filter is set. Now roundtripping is disabled if a post-processing filter is set. So this is fixed.
