### ISSUE TITLE
[kb for developers: Freme on Github] update article

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#250]
E-services is only reference to, but not explained explicitly. Maybe we should add this.

**Comment by ArneBinder** [comment]
I changed the topic. The whole [article](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-developers/freme-on-github.html) has to adapt the new architecture, e.g. remove depricated repositories and add new ones.

**Comment by jnehring** [comment]
Please do not remove deprecated repositoires because they contain issues that should not be deleted.

**Comment by ArneBinder** [comment]
I rearranged the repos and added missing ones.

ToDo: add description for:
- FREME parent
- FREME common
- e-Services
- Basic-Services

and link in all descriptions to the related (knowledge base) articles.

**Comment by ArneBinder** [comment]
implemented.

**Comment by jnehring** [comment]
I checked the article, it looks good!
