### ISSUE TITLE
[swagger-ui] fix collapsible General Information

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#252]
Examine why the `General Information` in the api doc of the branch `swagger-ui-new` does not collapse and fix this.

**Comment by ArneBinder** [comment]
The swagger-ui-branch was merged into the master, but this bug is still there.

**Comment by ArneBinder** [comment]
This is no bug, it has to be (re-)implemented: the collapse functionality for the other tag groups collapses only the list of endpoints, not the description of these. @jnehring should we expand the collapse functionality to the tag descriptions? This would implement this issue with at least efford.

**Comment by jnehring** [comment]
> @jnehring should we expand the collapse functionality to the tag descriptions?

sounds good, please implement it this way

**Comment by ArneBinder** [comment]
@jnehring it collapses again, please have a look.

**Comment by jnehring** [comment]
Looks good! I also re-added the "show/hide" buttons to each section. So this issue is finished.
