### ISSUE TITLE
Upload dataset tutorial invalid curl

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#254]
In the (create custom dataset tutorial](http://api.freme-project.eu/doc/current/tutorials/entity-recognition-against-custom-dataset.html#curl-examples) the first curl example does not have an authentication token and will therefore not work. Please do not add an actual token to the call but a placeholder like like "?token=YOUR_TOKEN_HERE".

**Comment by bgrusdt** [comment]
I have added the token parameter.
