### ISSUE TITLE
[kb for sysadmins] write article: Getting started for FREME system administrators

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#255]
Write a general overview article that mainly links to other already existing articles and summarizes all steps in the right order that need to be done in order to install FREME. 
We decided to put it into Knowledge Base / FREME for Sysadmins and link it from the knowledge base Overview.

**Comment by ArneBinder** [comment]
We should link to the following articles respectively the relevant paragraphs (please add missing):
- [Creating and Running a package](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/creating-and-running-a-freme-package.html)
- [FREME Configuration Options](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/configuration-options.html)
- [Initialising FREME](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/initialising-freme.html)
- [FREME NER: How to Install](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/freme-ner.html#how-to-install)
- [Running FREME on a webserver](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/install-freme-on-server.html)

**Comment by bgrusdt** [comment]
I have added the article to the repository, see [here](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/gettingStarted_SysAdmins.html). @jnehring  Can you check if it is okay? Thank you.

**Comment by jnehring** [comment]
Looks good! Some comments:
- One paragraph (marked in red in the screen shot) does not use the whole screen width. Please fix ![image](https://cloud.githubusercontent.com/assets/10537540/17016807/0b077376-4f31-11e6-97f2-5fdc6b6e3258.png)
- Please add a link to the [FREME packages article](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/freme-packages.html) to the section "Create and run the FREME package"

With these two things implemented you can close the issue.
