### ISSUE TITLE
[kb for api users] create article: Getting started for FREME API users

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#257]
write a short overview article containing the following:
- Link to Milans NIF slideshare from somewhere: http://de.slideshare.net/m1ci/nif-tutorial
- How to create an API request?
- Link to SPARQL filters
- Different input types / e-Internationalization, plaintext, NIF

**Comment by bgrusdt** [comment]
I have added the [article](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/gettingStarted_API-users.html). @jnehring can you have a look at it?  At the moment it is quite short, do you think there is something fundamental missing? Thank you

**Comment by jnehring** [comment]
- The example curl request points to freme-dev. Please make it point to freme-live.
- Input formats. Please change this section. Make a table of possible input types with columns input format, content-type header, remarks and rows:
  - NIF in several serialization formats (turtle, rdf-xml, ...)
  - Plaintext
  - e-Internationalization input formats. Write HTML, XLIFF 1.2, ... and link to the internationalization article so it is clear that the complete reference of formats is in the internationalization article..
- Output formats. Same as input formats but with Accept header:
  - NIF (turtle, xml-rdf, ...)
  - e-Internationalization output formats. Add to the remark that these can only be used when input foramt and output format are the same.
  - CSV, JSON, ... (SPARQL converter output formats)
- Please add a section about NIF with this content: The Natural Language Processing interchange format (NIF) is the default output format of all FREME e-Services. This is an RDF based data format that can be serialized in different formats such as turtle, rdf-xml and others. When you create a pipeline then internally the pipeline should speak NIF to make sure that all pipeline steps are compatible to each other. You can either parse the output of FREME directly using a suitable RDF library our you can use the Postprocessing Filters (link to knowledge base) to get a more traditional output format. You can find more information about NIF in these slides (link) or the official NIF reference.

**Comment by bgrusdt** [comment]
This is done, see [here](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/gettingStarted_API-users.html).

**Comment by jnehring** [comment]
Thank you! I will add some more information to the article.

**Comment by ArneBinder** [comment]
Does roundtripping work for XLIFF and ODT now? They are mentioned in [Output types](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/gettingStarted_API-users.html#output-types) ->e-internationalization.
But the last sentences of [this paragraph](api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/eInternationalisation.html#e-internationalisation) are indeed confusing/incorrect:

> New input and output formats are text/html, text/xml, application/x-xliff+xml and application/x-openoffice.
> 
> New output formats are text/html and text/xml. Note that this output format can be only used when the starting document is an HTML or XML file as well. This is a general rule when performing the round-tripping: input and output formats must be the same.

**Comment by jnehring** [comment]
> Does roundtripping work for XLIFF and ODT now? They are mentioned in Output types ->e-internationalization.

@katia-vistatec please comment.

**Comment by jnehring** [comment]
@bgrusdt some more changes
- Input and output type NIF: Please add all NIF formats which are
  - text/turtle (default)
  - application/ld+json
  - application/n-triples
  - application/rdf+xml
  - text/n3
- Column "Input format" in both tables should be labeled "Format"

**Comment by ArneBinder** [comment]
Why is there html embedded in html? Have a look at line 28 and 236 of [the article source file](https://raw.githubusercontent.com/freme-project/Documentation/master/_pages/knowledge-base/freme-for-api-users/gettingStarted_API-users.md).

**Comment by bgrusdt** [comment]
Shall we leave this open for adding more information? Or can I close it ? @ArneBinder you're right, thanks, it is not necessary to add the html declaration, I removed it.

**Comment by jnehring** [comment]
looks good. thanks
