### ISSUE TITLE
[kb for sysadmins] create article: FREME packages

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#260]
@jnehring Which content? List containing e-/b-services + configuration?

**Comment by jnehring** [comment]
The article should contain a description of the FREME packages in https://github.com/freme-project/freme-packages . freme-cloud-worker and freme-cloud-broker do not need a description right now.

**Comment by ArneBinder** [comment]
implemented.

**Comment by jnehring** [comment]
thank you
