### ISSUE TITLE
[tutorials: getting started with e-link] add template description from api doc

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#262]
I think we should move the explanation about @@@entity_uri@@@ and especially user defined parameters from the `POST /e-link/templates` of the interactive api doc, see last paragraph:

> In fact, each template should have the field @@@entity_uri@@@ which identifies an entity. When performing enrichment...

 to [this paragraph](http://api-dev.freme-project.eu/doc/tutorials/getting-started-with-e-link.html#what-is-a-template) of the e-link tutorial.
@jnehring what do you think?

**Comment by jnehring** [comment]
Good idea! Please dont move it but copy & paste it.

**Comment by ArneBinder** [comment]
I added a paragraph to [What is a template](http://api-dev.freme-project.eu/doc/tutorials/getting-started-with-e-link.html#what-is-a-template#what-is-a-template).
