### ISSUE TITLE
create page: freme-project.github.io/index.html

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#264]
Create the page according to [this](https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages). The page should simply re-direct to `http://www.freme-project.eu/`.

> Check how to do nice URL re-direct

Second step:
Create the documentation page directly on github to make it independent from the freme-project.eu domain, i.e. push the jekyll compiled `_site` folder to the documentation repository and link to `_site/home.html` page. Furthermore check/fix all internal links.

@fsasaki correct?

**Comment by ArneBinder** [comment]
@fsasaki please have a look at https://freme-project.github.io

**Comment by jnehring** [comment]
> please have a look at https://freme-project.github.io

Thanks Arne this looks good.

> Create the documentation page directly on github

I am not sure if this is works. Please try it out. But as far as I know we use some Jekyll extensions that are not compatible with GitHub Jekyll.

**Comment by ArneBinder** [comment]
@jnehring @bgrusdt I moved the current state of the documentation to github pages. I had to remove the [Jekyll Pages Directory Plugin](https://github.com/bbakersmith/jekyll-pages-directory) which does not seem to be mandatory. Furthermore, the [jekyll config](https://github.com/freme-project/freme-project.github.io/blob/master/_config.yml) changed a bit. Now, the `apiurl` contains the full url, `baseurl` and `url` are removed and replaced by `{{ site.github.url }}` in the code. This directs to `localhost` in local environments and is set correctly when processed by gh pages build.

We still have to check, if the page is really similar to the current docu page, but it looks not too bad. I just found an error with markdown lists, see the [knowledge base overview](https://freme-project.github.io/knowledge-base/overview.html), for instance. Also some internal links are still broken because there is no `/doc` subfolder anymore (also `home.html` had to be renamed to `index.html`, but this is already fixed), see below.

Furthermore, the [Travis](https://travis-ci.org) integration (which is a similar service like jenkins, but more general) provides the possibility to use [html-proofer](https://github.com/gjtorikian/html-proofer) on the fly. The current setting, for instance, presents all internal link errors (and some other stuff):
- ./_site/contact.html
  -  internally linking to info@freme-project.eu, which does not exist (line 562)
- ./_site/knowledge-base/freme-for-api-users/authentication.html
  -  internally linking to /doc/knowledge-base/freme-for-sysadmins/configuration-options.html, which does not exist (line 669)
  -  linking to /api-doc/full.html#!/Authenticate/post_authenticate, but !/Authenticate/post_authenticate does not exist (line 624)
  -  linking to /api-doc/full.html#!/User, but !/User does not exist (line 612)
  -  linking to /api-doc/full.html#!/User/delete_user_username, but !/User/delete_user_username does not exist (line 660)
  -  linking to /api-doc/full.html#!/User/post_user, but !/User/post_user does not exist (line 616)
  -  linking to /api-doc/full.html#!/User/put_user_username, but !/User/put_user_username does not exist (line 651)
- ./_site/knowledge-base/freme-for-api-users/filtering.html
  -  internally linking to /doc/api-doc/full.html#!General_Information, which does not exist (line 854)
  -  internally linking to /doc/knowledge-base/freme-for-api-users/authentication.html, which does not exist (line 800)
  -  trying to find hash of /doc/api-doc/full.html#!General_Information, but /home/travis/build/freme-project/freme-project.github.io/_site/doc/api-doc/full.html does not exist (line 854)
- ./_site/knowledge-base/freme-for-api-users/freme-ner.html
  -  image https://docs.google.com/drawings/d/1rBUpgRBlhh0We01PNOpKeCFVaoUEDi9sAah8E28r6WY/pub?w=378&h=401 does not have an alt attribute (line 583)
  -  internally linking to /doc/api-doc/simple.html#!/e-Entity/execute_0, which does not exist (line 730)
  -  linking to internal hash #configure-the-package that does not exist (line 571)
  -  trying to find hash of /doc/api-doc/simple.html#!/e-Entity/execute_0, but /home/travis/build/freme-project/freme-project.github.io/_site/doc/api-doc/simple.html does not exist (line 730)
- ./_site/knowledge-base/freme-for-api-users/xslt-transformation.html
  -  internally linking to /doc/knowledge-base/freme-for-api-users/authentication.html, which does not exist (line 820)
  -  internally linking to /doc/knowledge-base/freme-for-api-users/eInternationalisation.html#round-tripping-how-does-it-work, which does not exist (line 761)
  -  internally linking to /doc/knowledge-base/freme-for-api-users/gettingStarted_API-users.html#output-types-einternalisation, which does not exist (line 761)
  -  internally linking to /doc/tutorials/pipeline-entity-link.html, which does not exist (line 696)
  -  linking to /api-doc/full.html#!/Pipelining/post_pipelining_templates, but !/Pipelining/post_pipelining_templates does not exist (line 785)
  -  linking to /api-doc/full.html#resource_Toolbox/XSLT-Converter, but resource_Toolbox/XSLT-Converter does not exist (line 641)
  -  linking to /api-doc/full.html#resource_Toolbox/XSLT-Converter, but resource_Toolbox/XSLT-Converter does not exist (line 789)
  -  trying to find hash of /doc/knowledge-base/freme-for-api-users/eInternationalisation.html#round-tripping-how-does-it-work, but /home/travis/build/freme-project/freme-project.github.io/_site/doc/knowledge-base/freme-for-api-users/eInternationalisation.html does not exist (line 761)
  -  trying to find hash of /doc/knowledge-base/freme-for-api-users/gettingStarted_API-users.html#output-types-einternalisation, but /home/travis/build/freme-project/freme-project.github.io/_site/doc/knowledge-base/freme-for-api-users/gettingStarted_API-users.html does not exist (line 761)
- ./_site/knowledge-base/freme-for-developers/creating-a-basic-service.html
  -  internally linking to ../../freme-for-sysadmins/creating-and-running-a-freme-package.html, which does not exist (line 670)
- ./_site/knowledge-base/freme-for-developers/overview-of-the-freme-architecture.html
  -  image ../../img/freme-architecture.PNG does not have an alt attribute (line 583)
- ./_site/knowledge-base/freme-for-sysadmins/basic-services.html
  -  internally linking to ../freme-for-api-users/xslt-converter.html, which does not exist (line 1102)
- ./_site/knowledge-base/freme-for-sysadmins/gettingStarted_SysAdmins.html
  -  internally linking to ../freme-for-sysadmins/install-freme-on-server.html, which does not exist (line 576)
- ./_site/swagger/index.html
  -  image images/FREME_LogoHor_250px.png does not have an alt attribute (line 87)
  -  internal script lib/highlight.7.3.pack.js does not exist (line 21)
- ./_site/tutorials/entity-recognition-against-custom-dataset.html
  -  linking to /api-doc/full.html#!/e-Entity/createDataset, but !/e-Entity/createDataset does not exist (line 863)
- ./_site/tutorials/getting-started-with-e-link.html
  -  internally linking to /doc/api-doc/full.html#!/User/post_authenticate, which does not exist (line 896)
  -  internally linking to /doc/api-doc/full.html#!/User/post_authenticate, which does not exist (line 923)
  -  internally linking to /doc/api-doc/full.html#!/User/post_authenticate, which does not exist (line 948)
  -  internally linking to /doc/knowledge-base/freme-for-api-users/authentication.html, which does not exist (line 896)
  -  internally linking to /doc/knowledge-base/freme-for-api-users/authentication.html, which does not exist (line 923)
  -  internally linking to /doc/knowledge-base/freme-for-api-users/authentication.html, which does not exist (line 948)
  -  internally linking to /doc/knowledge-base/freme-for-api-users/filtering.html, which does not exist (line 973)
  -  trying to find hash of /doc/api-doc/full.html#!/User/post_authenticate, but /home/travis/build/freme-project/freme-project.github.io/_site/doc/api-doc/full.html does not exist (line 896)
  -  trying to find hash of /doc/api-doc/full.html#!/User/post_authenticate, but /home/travis/build/freme-project/freme-project.github.io/_site/doc/api-doc/full.html does not exist (line 923)
  -  trying to find hash of /doc/api-doc/full.html#!/User/post_authenticate, but /home/travis/build/freme-project/freme-project.github.io/_site/doc/api-doc/full.html does not exist (line 948)
- ./_site/tutorials/html-to-epub.html
  -  linking to /api-doc/full.html#!/e-Publishing/htmlToEPub, but !/e-Publishing/htmlToEPub does not exist (line 569)
  -  linking to /api-doc/full.html#!/e-Publishing/htmlToEPub, but !/e-Publishing/htmlToEPub does not exist (line 585)

htmlproofer 3.0.6 | Error:  HTML-Proofer found 42 failures!

**Comment by jnehring** [comment]
Right now we are doing a code freeze in the documentation repository until this activity is finished.

When the new homepage works, we should try if it is possible to have a dev and a live version. Live version should be in the master branch, dev version in the gh-pages branch. The two versions have different URLs.

**Comment by ArneBinder** [comment]
The second (dev) version is implemented, see https://freme-project.github.io/freme-project.github.io. But all internal links are still going to the master version. We have to add a variable like `subpath` to the jekyll `_config.yml` which contains `/freme-project.github.io` in the dev and an empty string in the live version. Then, `{{ site.subpath }}` has to be added to all internal urls.

**Comment by ArneBinder** [comment]
Implemented. @jnehring please have a look at
- https://freme-project.github.io
- https://freme-project.github.io/freme-project.github.io

Can we mark the Documentation repository as depricated?

**Comment by ArneBinder** [comment]
found one error: The links in the navigation bar of `https://freme-project.github.io/freme-project.github.io` still direct to versions of `https://freme-project.github.io`.

**Comment by ArneBinder** [comment]
The [dev version](http://api-dev.freme-project.eu/doc/) is implemented, but compilation will be still handled by jenkins. The [live version](https://freme-project.github.io) will be compiled via github pages. According to travis link check errors, there is #283.

**Comment by fsasaki** [comment]
Great work, thanks a lot, @ArneBinder .
