### ISSUE TITLE
[delete/ freme-ner/datasets] response body not displayed

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#266]
When a dataset is deleted with DELETE e-entity/freme-ner/datasets/{name} via postman, the following line is written to the body .
`The DatasetMetadata: NAME was removed sucessfully.'`

But in the documentation, it always prints 'no content' in the response body field...

**Comment by jnehring** [comment]
This is ok. The http status response code is 204 and i think that in this case no content should be send. so the bug is not in the documentation but in the api that sends content. but it is ok we do not need to change anything.
