### ISSUE TITLE
Add image to FREME NER documentation

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#267]
@bgrusdt Please add [this image](https://docs.google.com/drawings/d/1NxgQ7ltGT4ClxSPnq8O8y74jeY9RXJDw2SEprMtRGlk/edit) to the [documentation of FREME NER](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/freme-ner.html).

@m1ci is this the final version of the image?

**Comment by m1ci** [comment]
well, I guess yes, I received no comments so far.

**Comment by bgrusdt** [comment]
I have added the image to the website under the new headline 'Dependencies'.  The bigger size I could choose when publishing the googledoc was too big. Is it ok like this now?

**Comment by jnehring** [comment]
On my screen it is not easy to read the text on the image. Maybe the resolution of the image is not high enough? Or maybe there is strong compression? Please try to add the image in better quality.

**Comment by bgrusdt** [comment]
I have put the file as png into the img - folder. The quality is much better now.
