### ISSUE TITLE
Update article "run freme on a webserver"

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#268]
Please update the article [Running FREME on a webserver](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/install-freme-on-server.html).
- Update title to "Starting and running FREME"
- Add information about start_local.sh script

**Comment by bgrusdt** [comment]
I have added the information, see [here](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/install-freme-on-server.html).  
I will rename the file itself as well and update the links referencing this article.

**Comment by bgrusdt** [comment]
This is done. @jnehring  if my notes are alright, I'd close  this issue.

**Comment by jnehring** [comment]
thank you !
