### ISSUE TITLE
[freme-ner] Update description of the dataset parameter.

### ISSUE THREAD

**Issue by sandroacoelho** [freme-project/freme-project.github.io#270]

**Comment by sandroacoelho** [comment]
Linking Method (linkingMethod) is a configurable parameter that aims to add extras approaches on entity linking step to improve recall. In NER systems, recall is similarly the number of names in the gold standard that appear at exactly the same location in the predictions.

FREME-NER provides the following approaches to leverage the recall:
-  **SurfaceFormSimilarity1**: leaning on Jaro–Winkler string similarity/distance, FREME-NER computes a distance between selected entities in Solr and the annotated entities;

**Comment by sandroacoelho** [comment]
Hi @bgrusdt, @m1ci 

Could you please add this explanation to the API documentation?

**Comment by jnehring** [comment]
@sandroacoelho I think that there is also a parameter for MFS - Most Frequent Sense method. Can you add the description for this parameter also please?
When this is done @bgrusdt can add the parameter to the API documentation.

**Comment by sandroacoelho** [comment]
Sure. Let's check it out

**Comment by sandroacoelho** [comment]
Linking Method (linkingMethod) is a configurable parameter that aims to add extras approaches on entity linking step to improve recall. In NER systems, recall is similarly the number of names in the gold standard that appear at exactly the same location in the predictions.

FREME-NER provides the following approaches to leverage the recall:
- **Most Frequent Sense (MFS):** this approach is used by default. MFS just picks the top result from Solr query. Left blank if you want to use it.
- **SurfaceFormSimilarity1:** leaning on Jaro–Winkler string similarity/distance, FREME-NER computes a distance between selected entities in Solr and the annotated entities;

**Comment by jnehring** [comment]
thank you @sandroacoelho 

@bgrusdt when the documentation code freeze is over then please add this parameter to the [api documentation](api-dev.freme-project.eu/doc/api-doc/full.html)

**Comment by m1ci** [comment]
The description is too technical, in other words, for end-users it is irrelevant "how linking is done" but what they are interested is "how it will influence the results". I suggest following description:

Linking Method (linkingMethod) is a configurable parameter that can be used to choose preferred entity linking method. Depending on dataset and the content you want to process, one linking might provide better results than other. While one approach could aim at higher recall, the other might target higher precision. 

So far, you can choose between following linking approaches:
- **Most Frequent Sense (MFS):** this approach is used by default. It will link the mention with the most frequent sense entity in the knowledge bases. Left blank if you want to use it.
- **SurfaceFormSimilarity1:** this approach aims at higher precision. It performs linking by combining the most frequent sense approach and the string similarity distance between the entity mention and the label associated with the link in the knowledge base. You can use this approach by specifying the value of the linkingMethod parameter to `SurfaceFormSimilarity1`.

**Comment by jnehring** [comment]
ok thanks for the update.

I have one question about the MFS: Where is this information stored? When I upload a dataset, then I assume that the SKOS file does not store this information?

**Comment by m1ci** [comment]
we have this info only for DBpedia and it can be found here
http://downloads.dbpedia.org/2015-04/ext/nlp/abstracts/surfaceforms/
This is part of the DBpedia abstracts dataset
http://downloads.dbpedia.org/2015-04/ext/nlp/abstracts/
The count info is stored in the `count` field in the Solr documents.

**Comment by jnehring** [comment]
Ok. So for all datasets apart from dbpedia, the disambiguation method relies on a non-initialized field in the Solr index? This means the default disambiguation method is random for these datasets?

One more question: When I upload the dbpedia dataset via the API, does this initialize the `count`field for the Solr documents? Or how does this work?

**Comment by m1ci** [comment]
> Ok. So for all datasets apart from dbpedia, the disambiguation method relies on a non-initialized field in the Solr index?

No, it is initialized to 1.

> This means the default disambiguation method is random for these datasets?

Its not random but its based on the Solr similarity.

> One more question: When I upload the dbpedia dataset via the API, does this initialize the countfield for the Solr documents? Or how does this work?

Yes, it is initialized to 1. If you want to benefit from the pairCount dataset, you'll need to index it manually.

**Comment by bgrusdt** [comment]
@m1ci  I have added your description to the [API-documentation](http://api-dev.freme-project.eu/doc/api-doc/full.html#!/e-Entity/executeFremeNer). So can I close this?

**Comment by m1ci** [comment]
I would say yes.

**Comment by bgrusdt** [comment]
Ok thanks.

**Comment by ArneBinder** [comment]
@m1ci  @jnehring  At the moment the parameter `linkingMethod` is checked just for similarity to `SurfaceFormSimilarity1`. The api-doc doesnt reflect this clearly e.g. that **any other** value than `SurfaceFormSimilarity1` will implicate MFS.

**Comment by jnehring** [comment]
i think the documentation is quiet clear
