### ISSUE TITLE
XSLT converter in the documentation

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#272]
@ArneBinder Please add a knowledge base article about xslt converter. It should explain
- What the XSLT converters can do and a brief overview about the API endpoints with links to API documentation.
- Example pipeline. I think you can re-implement one of the pipelines from [xml to rdf tutorial](http://api-dev.freme-project.eu/doc/freme-showcase/xml-to-rdf.html).
- Which ready to use stylesheets exists

Please add the XSLT stylesheets to [initialising FREME](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/initialising-freme.html) and the new input types to the list of input types in [Getting started for FREME API users](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/gettingStarted_API-users.html).

@fsasaki do you have any more content you would like to add to the article?

**Comment by fsasaki** [comment]
Sounds good, thanks.

2016-07-21 11:06 GMT+02:00 Jan Nehring notifications@github.com:

**Comment by ArneBinder** [comment]
@fsasaki the update of the description of converters via the api-doc is fixed. I also fixed this for the postprocessing sparql filters.

**Comment by ArneBinder** [comment]
ToDo: add pipelien paragraph

**Comment by jnehring** [comment]
@ArneBinder please change the title. I think "XSLT transformation via FREME" is more suitable then "Input transformation with XSLT" because the transformation can be applied to the output also.

The article is [here](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/xslt-transformation.html).

**Comment by ArneBinder** [comment]
> add the new input types to the list of input types in Getting started for FREME API users.

I'm not able to extend the table without producing errors.

**Comment by ArneBinder** [comment]
ToDo: add pipeline

**Comment by jnehring** [comment]
Please add the pipeline for docbook and output type 3 from http://api-dev.freme-project.eu/doc/freme-showcase/xml-to-rdf.html . You can leave the other parameters the same as in the example.

**Comment by ArneBinder** [comment]
I added the xliff pipeline instead of the docbook, because there is already a [working version](http://api-dev.freme-project.eu/current/pipelining/templates/69) in the database.

**Comment by ArneBinder** [comment]
@jnehring please review the paragraph [XSLT converter in a pipeline](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/xslt-transformation.html#xslt-converter-in-a-pipeline).

**Comment by jnehring** [comment]
> @jnehring please review the paragraph XSLT converter in a pipeline.

looks good. can we close this issue or is there still something open?
