### ISSUE TITLE
Add more groups to api documentation - toolbox

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#273]
In [api documentation - toolbox](http://api-dev.freme-project.eu/doc/api-doc/full.html#/Toolbox) are many different api endpoints in the same heading. please add groups and a short caption to each group:
- Toolbox / Postprocessing Filter
- Toolbox / XSLT Converter
- Toolbox / NIF-Converter

**Comment by bgrusdt** [comment]
This is implemented. Can I close the issue?

**Comment by jnehring** [comment]
Finished. Thank you!
