### ISSUE TITLE
Wrong default value for Content-Type header

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#274]
The API documentation has the wrong default value for the Content-Type header. The default value is "text/turtle" for these endpoints:
- POST /e-entity/dbpedia-spotlight/documents 
- POST /e-entity/freme-ner/documents
- POST /e-terminology/tilde
- POST /e-translation/tilde

Please fix this.

**Comment by bgrusdt** [comment]
I have changed the values. But for the first endpoint, dbpedia-spotlight/documents, we have plaintext as default body. @jnehring Shall I change this to turtle or do we want to keep it as it is?

**Comment by jnehring** [comment]
> But for the first endpoint, dbpedia-spotlight/documents, we have plaintext as default body

Oh thats a bug. Please set default input format turtle in the documentation. To update the code I created https://github.com/freme-project/e-services/issues/25

**Comment by bgrusdt** [comment]
This is done. I changed the default example + content-type in the documentation to turtle.
