### ISSUE TITLE
Add Postman Collection

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#275]
Please add the postman collection to this article: http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/gettingStarted_API-users.html together with a paragraph on how the postman collection works and how to adjust the urls to a new API.

**Comment by ArneBinder** [comment]
Implemented. @jnehring please look at [this paragraph](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/gettingStarted_API-users.html#freme-postman-collection).
I moved all postman collections to _pages/resources/postman. I wasnt sure about deleting the old ones. I think they arose from different use cases. @jnehring what do you think?

**Comment by jnehring** [comment]
Thanksk @ArneBinder! I added a few sentences to the paragraph.

I could not get the postman collection running. Lets try it together.

**Comment by ArneBinder** [comment]
@jnehring please retry.

**Comment by jnehring** [comment]
Now it works, thanks! I just changed in the article the proposed value for baseUrl from `http://api.freme-project.eu/current` to `api.freme-project.eu/current`.
