### ISSUE TITLE
Simple API doc does not work

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#281]
http://api-dev.freme-project.eu/doc/api-doc/simple.html#!/e-Entity/executeSpotlightNer

**Comment by ArneBinder** [comment]
@jnehring I can not reproduce this. Is it still present?

**Comment by jnehring** [comment]
Still happens in Google Chrome. In Firefox it works.

![image](https://cloud.githubusercontent.com/assets/10537540/17697110/17af380c-63b3-11e6-8e1e-bf79300fd7bc.png)

**Comment by ArneBinder** [comment]
This was just a caching issue, not a bug.
