### ISSUE TITLE
Update documentation homepage

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#282]
Update documentation according to moving the hoempage to a GitHub pages site.

[Maintaining the documentation project](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-developers/maintaining-the-documentation-project.html)

[How to add documentation](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-developers/how-to-add-documentation.html)

[FREME on GitHub](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-developers/freme-on-github.html)

**Comment by ArneBinder** [comment]
I have done the modifications. @jnehring please have a look and close, if it looks ok.

**Comment by jnehring** [comment]
looks good, thank you
