### ISSUE TITLE
Update documentation of NIF Converter

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#284]
Please update the documentation of the [nif converter](http://api-dev.freme-project.eu/doc/api-doc/full.html#!/Toolbox%2FNIF-Converter/post_toolbox_nif_converter):
### Implementation notes:

This endpoint allows to convert plain text, a document in any format supported by e-Internalisation(link) or in the RDF formats supported by FREME into a NIF document with the RDF serialisation format specified by the accept header. Further it can convert all data formats supported by Apache Tika to NIF, you can find a list of formats here: https://tika.apache.org/1.13/formats.html

To convert plaintext to NIF, one RDF format to another, or to use e-Internationalization, you specify the input format in the Content-Type header, output format in the Accept header and send the data to convert in the document body.

To use Apache Tika, you specify a multipart request and send the file in the document body. The format of the input file will be determined by the filename. Further you need to set query string parameter `informat=TIKAFile`. The output format is specified by the Accept header.

**Example cURL to convert plaintext to Turtle**

Please add an example

**Example cURL to convert HTML to RDF-XML, using e-Internationalization**

Please add an example, using e-Internationalization

**Example cURL to convert PDF to Turtle**

```
curl -X POST -F "inputFile=@source_pdf.pdf" "http://api.freme-project.eu/current/toolbox/nif-converter?informat=TIKAFile" -H "Accept: text/turtle"
```
### Parameters

Please add the informat parameter. Is it possible to implement it with two values - "TIKAFile" when you want to use Tika and blank when you do not want to use it? I hope the blank value of informat does not override the Content-Type header.

**Comment by bgrusdt** [comment]
The description is added. To be done : add informt parameter. Check newlines in curl examples and provide the example html file.

**Comment by fsasaki** [comment]
The linked HTML and PDF files
http://api-dev.freme-project.eu/doc/api-doc/someText.html
http://api-dev.freme-project.eu/doc/api-doc/source_pdf.pdf
are not on the server, it seems.

2016-08-18 17:46 GMT+02:00 bgrusdt notifications@github.com:

**Comment by fsasaki** [comment]
[test.pdf](https://github.com/freme-project/freme-project.github.io/files/426474/test.pdf)
I tried the request with the attached PDF

> curl -X POST -F "inputFile=@test.pdf" "http://api.freme-project.eu/current/toolbox/nif-converter?informat=TIKAFile" -H "Accept: text/turtle"

I get an exception

> {
>   "exception": "org.springframework.http.converter.HttpMessageNotReadableException",
>   "path": "/toolbox/nif-converter",
>   "message": "Required request body content is missing: org.springframework.web.method.HandlerMethod$HandlerMethodParameter@cc41d2a9",
>   "error": "Bad Request",
>   "status": 400,
>   "timestamp": 1471590181385
> }

Is this an error in the implementation or is my request wrong?

**Comment by jnehring** [comment]
@fsasaki please use the dev API. 

```
curl -X POST -F "inputFile=@test.pdf" "http://api-dev.freme-project.eu/current/toolbox/nif-converter?informat=TIKAFile" -H "Accept: text/turtle"
```

**Comment by bgrusdt** [comment]
I changed the examples such that it is not necessary to download any file, the html is inside the curl command now and the user is asked to use his or her own pdf file. 
I added the informat parameter to the documentation.  When TIKAFile is not chosen, informat is not taken into account. 
@jnehring  Shall we add the pdf file and the inputFile parameter to the documentation because otherwise the TIKAFile parameter cannot be used, or am I wrong?

**Comment by jnehring** [comment]
> @jnehring Shall we add the pdf file and the inputFile parameter to the documentation because otherwise the TIKAFile parameter cannot be used, or am I wrong?

If it works out, then fine, please add the parameter to the documentation. Note that in this case the request needs to be a multipart request. But when it is too difficult to have an API request that is either multipart of normal POST request, then do not invest too much work in exposing this functionality in the interactive API documentation.

**Comment by bgrusdt** [comment]
I've added the functionality to the [documentation](http://api-dev.freme-project.eu/doc/api-doc/full.html#!/Toolbox%2FNIF-Converter/post_toolbox_nif_converter). Both requests are possible now, but when you made a multipart request, the website has to be loaded again before another normal POST request can be made. So far I haven't figured out how this can be changed. @jnehring  do you think it is ok like this or shall I check how to solve this?

**Comment by fsasaki** [comment]
Thanks! Sorry that I mixed up freme dev and freme live - @jnehring 's request at https://github.com/freme-project/freme-project.github.io/issues/284#issuecomment-241330861 works fine.

**Comment by jnehring** [comment]
Maybe you can enable the multipart request when you add a Content-Type header "multipart/form-data" ?

**Comment by jnehring** [comment]
This issue is solved. you can ignore my last comment
