### ISSUE TITLE
Problem in API users getting started

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#285]
There is something wrong in the [API users getting started guide](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/gettingStarted_API-users.html), see screenshot:

![image](https://cloud.githubusercontent.com/assets/10537540/17887816/7768c658-6928-11e6-8d7a-874c28668e42.png)

Please fix

**Comment by ArneBinder** [comment]
This should be implemented.

**Comment by jnehring** [comment]
looks good thanks
