### ISSUE TITLE
authenticated requests : no response from server

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#286]
The request [POST e-link/templates](http://api-dev.freme-project.eu/doc/api-doc/full.html#!/e-Link/createTemplate) , done from the api website, with the given example and default parameters results in:
- ResponseHeader: 
  {
  "error": "no response from server"
  }
- Response code: 0
- Response Header: No content

But running the generated curl works fine:  

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'X-Auth-Token: YOUR_TOKEN' -d ' {
  "query": "PREFIX dbpedia:  \n PREFIX dbpedia-owl:  \n PREFIX rdf:  \n PREFIX geo:  \n CONSTRUCT \n { \n ?museum  <@@@entity_uri@@@> . \n } \n WHERE \n { \n <@@@entity_uri@@@> geo:geometry ?citygeo . \n ?museum rdf:type  . \n ?museum geo:geometry ?museumgeo . \n FILTER ((?museumgeo, ?citygeo, 10)) \n } \n LIMIT 10",
  "endpoint": "http://dbpedia.org/sparql/",
  "label": "template title",
  "description": "template description",
  "endpointType": "sparql",
  "visibility": "public"
} ' 'https://api-dev.freme-project.eu/current/e-link/templates/?visibility=public&description=testing'
```

The problem seems to be only when a token is used since requests without tokens seem to work fine.

**Comment by jnehring** [comment]
Maybe related to https://github.com/freme-project/basic-services/issues/91 ?

**Comment by jnehring** [comment]
Now it seems to work again. @ArneBinder can you please test it again?

**Comment by ArneBinder** [comment]
It works. The problem was, that `https` was set as protocol, but this does not work for dev.

**Comment by jnehring** [comment]
Will test again

**Comment by jnehring** [comment]
fixed, see https://github.com/freme-project/basic-services/issues/97
