### ISSUE TITLE
update dataset description page

### ISSUE THREAD

**Issue by m1ci** [freme-project/freme-project.github.io#288]
1) At http://api.freme-project.eu/doc/current/api-doc/list-datasets.html should be listed only the dataset converted within the FREME project, or datasets used in FREME?
Note that VIAF, ONLD and the Geopolitical ontology have not been converted during FREME.

2) GRID description is missing

Please add grid to the list of available datasets.
Description: Global Research Identifier Database (GRID) provides identifiers for world research organizations.
URL: https://www.grid.ac/

**Comment by jnehring** [comment]
> 1) At http://api.freme-project.eu/doc/current/api-doc/list-datasets.html should be listed only the dataset converted within the FREME project, or datasets used in FREME?

no, we want to list all datasets on the page. anyways i think we will work over the page.

@ArneBinder please add the GRID dataset to https://api-dev.freme-project.eu/doc/api-doc/list-datasets.html

**Comment by ArneBinder** [comment]
This is implemented.

**Comment by jnehring** [comment]
thank you
