### ISSUE TITLE
[kb-for-users/pipelines] create article

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#289]
Create an article about FREME pipelines, similar to the [XSLT Converter article](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/xslt-transformation.html) and the [filtering article](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/filtering.html).
- Write a general description about pipelines
- link to [pipeline tutorial](http://api-dev.freme-project.eu/doc/tutorials/pipeline-entity-link.html)
- Move some content from [pipeline tutorial](http://api-dev.freme-project.eu/doc/tutorials/pipeline-entity-link.html) step 3 (use of `useI18n`)
- explain parametrization, see https://github.com/freme-project/basic-services/issues/77
- describe pipeline management

@jnehring something to add?

**Comment by jnehring** [comment]
I will add contents from the pipelines presentation I am working on right now.

**Comment by jnehring** [comment]
Here is additional material for the article. You can ignore the slides 1-15, pipelining starts on slide 16. You can find example pipelines in the postman collection.

https://drive.google.com/drive/folders/0B8CeKhHCOSqUYzdydnJJSVRlY0U

**Comment by ArneBinder** [comment]
Implemented, @jnehring please review [the article](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/pipelines.html).

**Comment by jnehring** [comment]
good article. thank you.

@bgrusdt please add a link to this article to the introduction of the [e-entity - e-link pipeline tutorial](https://api-dev.freme-project.eu/doc/tutorials/pipeline-entity-link.html).
