### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#290]
html-proofer reports the following (see [this](https://travis-ci.org/freme-project/freme-project.github.io/builds/156260042) for the full log):
- ./_site/api-doc/list-datasets.html
  -  External link http://freme.aksw.org/datasets/orcid/ failed: 503 No error
- ./_site/api-doc/list-templates.html
  -  External link http://rv2622.1blu.de:5000/dbpedia-categories failed: got a time out (response code 0)
- ./_site/tutorials/getting-started-with-e-link.html
  -  External link http://rv2622.1blu.de:5000/ failed: got a time out (response code 0)
  -  External link http://rv2622.1blu.de:5000/cordis failed: got a time out (response code 0)
  -  External link http://rv2622.1blu.de:5000/orcid failed: got a time out (response code 0)

htmlproofer 3.0.6 | Error:  HTML-Proofer found 5 failures!

@jnehring I can not access any page at `http://rv2622.1blu.de` or `http://freme.aksw.org/datasets/orcid/`. Any ideas?

**Comment by m1ci** [comment]
> External link http://freme.aksw.org/datasets/orcid/ failed: 503 No error

Please update the URL to http://rv2622.1blu.de/datasets/orcid/

> External link http://rv2622.1blu.de:5000/ failed: got a time out (response code 0)

fixed

> External link http://rv2622.1blu.de:5000/cordis failed: got a time out (response code 0)

fixed

> External link http://rv2622.1blu.de:5000/orcid failed: got a time out (response code 0)

fixed

**Comment by ArneBinder** [comment]
@m1ci thanks a lot!
