### ISSUE TITLE
Document nif-version parameter

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#294]
Please add a query string parameter nif-version to the API documentation of each of these endpoints. It has values "" (blank), "2.0" and "2.1". The description is: "Specify the nif version that the endpoint should produce. Can be "2.0" or "2.1". Leave blank for the default value "2.0".

Currently this waits for https://github.com/freme-project/e-services/issues/31 and https://github.com/freme-project/basic-services/issues/98 (for the nif-converter)

This parameter needs to be added to
- POST /e-entity/dbpedia-spotlight/documents POST /e-entity/freme-ner/documents Entity recognition and linking using Freme-NER engine.
- POST /e-entity/freme-ner/documents
- POST /e-terminology/tilde 
- POST /e-translation/tilde
- POST /toolbox/nif-converter

**Comment by ArneBinder** [comment]
Just to note: The nif-version is handled by BaseRestController.normalizeNif() when passing the parameters map like it is used [here](https://github.com/freme-project/freme-ner/blob/master/src/main/java/org/elinker/core/rest/FremeNerEnrichment.java#L191-L192) and accessible via nifParameter.getNifVersion(), have a look at [this](https://github.com/freme-project/freme-ner/blob/master/src/main/java/org/elinker/core/rest/FremeNerEnrichment.java#L216), for instance.

In this way, it is a implemented for:
- POST /e-entity/freme-ner/documents
- POST /e-terminology/tilde
- POST /e-translation/tilde
- POST /toolbox/nif-converter

Still missing: `POST /e-entity/dbpedia-spotlight/documents`

**Comment by jnehring** [comment]
This issue is about API documentation of the new parameter. I think the documentation did not change yet.

**Comment by jnehring** [comment]
Please remove dbpedia spotlight because this is not implemented yet (see https://github.com/freme-project/e-services/issues/31)

**Comment by jnehring** [comment]
this task is finished
