### ISSUE TITLE
Translation tutorial does not work

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#297]
When I open the [translation tutorial](https://freme-project.github.io/tutorials/translate_EN-NL_including_terminology.html) in google chrome / ms windows 8 and click the "try it out" button then the page scrolls to the top and no API call is executed. Maybe this is related to #292

**Comment by ArneBinder** [comment]
> Maybe this is related to #292

no, I fixed the tutorial page, now it displays:

```
{
  "exception": "eu.freme.common.exception.ExternalServiceFailedException",
  "path": "/e-translation/tilde",
  "message": "External service failed: {\"Message\":\"System not available for requested language pair\"}",
  "error": "Not Found",
  "status": 404,
  "timestamp": 1474554585701
}
```

**Comment by andish** [comment]
MT Development environment has only EN-DE system available. Freme DEV is using it currently. In the middle of next week we will release MT and also FREME dev server will have then all FREME MT systems, including also EN-NL which is used in this tutorial.

**Comment by ArneBinder** [comment]
This works again. Can we close it?

**Comment by jnehring** [comment]
I just changed the Tilde API endpoint to live. So this issue is fixed.

**Comment by borriellom** [comment]
The tutorial is not working again and I'm getting the same error in Ocelot when sending a request to the e-Translation service. I always get the error whatever language pair I choose (I'm only using language pairs listed in the "Available Systems" section [here](https://services.tilde.com/translationsystems).

I don't know if this issue should be reopened or if systems are just temporarily down.

Note that I'm using public systems (empty key parameter) and FREME "current" version.

**Comment by jnehring** [comment]
The issue is fixed on freme-dev. freme-live still uses the development version of Tildes MT API. So currently only the [dev version of the tutorial](https://api-dev.freme-project.eu/doc/tutorials/translate_EN-NL_including_terminology.html) works.

Thanks for the reminder. I will reopen the issue and close it when it is really fixed after next release.

Welcome back @borriellom :)

**Comment by borriellom** [comment]
Thanks :)

**Comment by jnehring** [comment]
Fixed through https://github.com/freme-project/FREMECommon/issues/38
