### ISSUE TITLE
External link http://europeana.ontotext.com/sparql failed

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#298]
[Travis reports](https://travis-ci.org/freme-project/freme-project.github.io/builds/161045717):
- ./_site/api-doc/list-templates.html
  -  External link http://europeana.ontotext.com/sparql failed: 404 No error

It looks like the Europeana sparql endpoint is moved to http://sparql.europeana.eu/sparql. If this is correct, it would effect the functionality of all e-Link templates using this one.

**Comment by jnehring** [comment]
@bgrusdt please update the endpoint in the e-link templates on
- freme-live
- freme-dev

It is not necessary to update the initialising freme sql files.

**Comment by bgrusdt** [comment]
I updated the europeana endpoint in the templates of live and dev to: **http://sparql.europeana.eu**.
I checked it and it works again.

**Comment by ArneBinder** [comment]
[Travis](https://travis-ci.org/freme-project/freme-project.github.io/builds/166476034) reports still the same failure.

**Comment by jnehring** [comment]
i will take a look at this

**Comment by jnehring** [comment]
@bgrusdt please update the link on https://freme-project.github.io/api-doc/list-templates.html
