### ISSUE TITLE
can't retrieve token

### ISSUE THREAD

**Issue by m1ci** [freme-project/freme-project.github.io#299]
Im trying to authenticate (retrieve token) using FREME live documentation page at https://freme-project.github.io/api-doc/full.html#!/User/post_user but I get "no content" for response body and {  "error": "no response from server" } as response header.

**Comment by m1ci** [comment]
via curl works, so probably there is CORS issue

**Comment by jnehring** [comment]
looks like a cors issue. The Javascript console reports

```
XMLHttpRequest cannot load https://api.freme-project.eu/current/authenticate. Request header field X-Auth-Password is not allowed by Access-Control-Allow-Headers in preflight response.
```

**Comment by m1ci** [comment]
yes, all sent/received headers should be allowed in the pre-flight request via Access-Control-Allow-Headers

**Comment by jnehring** [comment]
This is fixed on freme-dev. Will try in the next release if this will be fixed on freme-live also.

**Comment by jnehring** [comment]
fixed by https://github.com/freme-project/technical-discussion/issues/125
