### ISSUE TITLE
Test documentation homepage

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#302]
Please test the interactive parts of the live documentation: freme-project.github.io
- [full api documentation](https://freme-project.github.io/api-doc/full.html#!/Toolbox%2FNIF-Converter/post_toolbox_nif_converter)
- Tutorials
- Showroom

**Comment by bgrusdt** [comment]
Update Template in Tutorial Section/getting started with e-link doesnt work on live, but already fixed on dev.

**Comment by bgrusdt** [comment]
Enrich and Simplify in Tutorial/getting started with e-link doesnt work on live but already works on dev
