### ISSUE TITLE
[full api] e-entity/dbpedia-spotlight/documents fails

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#305]
[dbpedia-spotlight request](https://freme-project.github.io/api-doc/full.html#!/e-Entity/executeSpotlightNer) with default values exits with the following error message on both freme-live and freme-dev:

```
{
  "exception": "eu.freme.common.exception.ExternalServiceFailedException",
  "path": "/e-entity/dbpedia-spotlight/documents",
  "error": "Bad Gateway",
  "status": 502,
  "timestamp": 1476099660064
}
```

**Comment by jnehring** [comment]
The error message indicates that DBPedia spotlight is not reachable. This is not a bug on the FREME side but on the DBPedia spotlight side. I am sure that the endpoint will be reachable again in the future but we have no influence on this.
