### ISSUE TITLE
[e-link/templates] delete template/pipeline shows wrong response

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#307]
When I delete a template on the [full API](https://freme-project.github.io/api-doc/full.html#/) the reponse I get is:

Response Body: no content
Response Headers: "error": "no response from server"
Response Code: 0

But the template was actually deleted and the response on the terminal from the curl command is as it is supposed to be: _The Template: XX was removed sucessfully._

```
curl -X DELETE --header 'Accept: application/json' --header 'X-Auth-Token: YOUR_TOKEN' 'https://api.freme-project.eu/current/e-link/templates/4500'
```

**Comment by bgrusdt** [comment]
The same happens for updating a template. Updating works with Postman.

**Comment by bgrusdt** [comment]
The same happens when deleting pipelines.

**Comment by jnehring** [comment]
dublicate of #303
