### ISSUE TITLE
[live docu] different versions

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#308]
Are there currently two live versions of the docu?
[This page at freme-project.github.io](https://freme-project.github.io/tutorials/translate_EN-NL_including_terminology.html) is different from [the same page at api.freme-project.eu/doc/current](https://api.freme-project.eu/doc/current/tutorials/translate_EN-NL_including_terminology.html), compare the sc via diff. (Also, the later does not work correctly.)
Sorry for the noise, if this is intended.

**Comment by jnehring** [comment]
The version at http://api.freme-project.eu/doc/current is still version 0.9 and outdated. The documentation homepage moved to https://freme-project.github.io

I setup a redirect so http://api.freme-project.eu/doc/current redirects to https://freme-project.github.io
