### ISSUE TITLE
[live docu] external url fails

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#309]
At any doc page of [https://freme-project.github.io/](https://freme-project.github.io/), the menu link `FREME Showroom -> FREME Workflow Editor` fails.

The variable `pages_url` defined [here](https://github.com/freme-project/freme-project.github.io/blob/dev/_includes/header.html#L20) is unnecessary and causes errors in live version like the one mentioned because of [this line](https://github.com/freme-project/freme-project.github.io/blob/dev/_includes/header.html#L54). If the variable will be simply removed, it should work.

Furthermore, the live doc points to the dev version of the freme workflow editor. If this is uninted, it can be changed by modifying the value `externurl` in [this file](https://raw.githubusercontent.com/freme-project/freme-project.github.io/dev/freme-showcase/freme-workflow-editor.md) to `{{site.apiProtocol}}://{{site.apiHost}}/freme-workflow-editor/`, for instance (or just hardcode it to `https://api.freme-project.eu/freme-workflow-editor/`).

**Comment by jnehring** [comment]
The fix @ArneBinder did not work. It led to a page like this:

![image](https://cloud.githubusercontent.com/assets/10537540/19483272/15919b50-9554-11e6-9e43-b36bc265a4ca.png)

I added a javascript snipped on an empty page that redirects to the external url. I found this tip in a forum. Other solutions include plugins so this was the easiest solution.

**Comment by ArneBinder** [comment]
@jnehring did you remove all usages of the variable when you deleted it, like [this one](https://github.com/freme-project/freme-project.github.io/blame/dev/_includes/header.html#L54)? Otherwise, the page can not be parsed completely and just the half header will be shown because the Javascript fails. By doing so, no special forwarding should be necessary, it works like intended from Jonathan with the jekyll variable externurl.

**Comment by jnehring** [comment]
i think we can leave it like it is. thank you @ArneBinder
