### ISSUE TITLE
Updating templates and pipelines doesnt work  from full API 

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#310]
When I update a template or pipeline from the [full API](https://freme-project.github.io/api-doc/full.html#!/Pipelining/put_pipelining_templates_id), there is no change in the database. 
But when using Postman, it does work. 

This response is shown by the API:
Response Body: no content
Response Headers: "error": "no response from server"
Response Code: 0

**Comment by bgrusdt** [comment]
The same is the case for sparqlconverters.

**Comment by jnehring** [comment]
This is a dublicate of #303
