### ISSUE TITLE
[Showroom] Reuse of Enrichment Information uses dbpedia-spotlight

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#311]
Dbpedia-spotlight doesn't work at the moment and it is used in this example. I think we should update the example such that we can be sure that it works.

**Comment by bgrusdt** [comment]
This is fixed, see [here](https://api-dev.freme-project.eu/doc/freme-showcase/reuse-of-enrichment-information.html). Now, Freme-NER is used instead of Dbpedia-spotlight.

**Comment by bgrusdt** [comment]
There seems to be something wrong with displaying the response.

**Comment by bgrusdt** [comment]
I tried it again and it does work. Though, i keep this open since I don't know why it had stopped working.

**Comment by jnehring** [comment]
Maybe FREME NER restarted when you tried it the last time

**Comment by jnehring** [comment]
This works now. I guess that temporarily either freme ner or the sparql endpoint behind the elink template was down
