### ISSUE TITLE
review article about loading data into solr and virtuoso

### ISSUE THREAD

**Issue by bgrusdt** [freme-project/freme-project.github.io#325]
I open this issue in order to remind us to review the short article I wrote about how to load data into virtuoso and solr. 
I wrote the article because I'd like to show the  mysql commands that add the metadata for the linking datasets to the mysql database in the webinar such that people can just copy them.

**Comment by fsasaki** [comment]
Thanks, @bgrusdt - do you have a link to the article?

**Comment by bgrusdt** [comment]
@fsasaki  sure, see [here](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/initialising-freme.html) .

**Comment by fsasaki** [comment]
Thanks, Britta. The linked article
https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/freme-ner.html#prerequisites
points to the latest solr version. From my understanding this does not work and we need a pre-configured solr?

**Comment by bgrusdt** [comment]
@fsasaki I am not 100 % sure, but I think you are right. The linked article is old, we should update it. I'd talk to Jan first and update it when we are all back.

**Comment by fsasaki** [comment]
> I'd talk to Jan first and update it when we are all back.

Sure - if this does not influence the content of the webinar. The webinar readers / listeners will need to know which version of solr to use - "our" preconfigured version or the latest official build version.

**Comment by jnehring** [comment]
The article looks good.

I have used Solr 5, I need to look up which version exactly. But I did not use the latest version, the latest version is 6.something. Also I copied more data then just the schema. I followed [this script](https://github.com/freme-project/freme-docker/blob/master/freme-solr/Dockerfile). But I am not sure if this is needed. Did it work out for you?

**Comment by jnehring** [comment]
The version is 5.2.1. The installation documentation will be updated, see this issue: https://github.com/freme-project/freme-project.github.io/issues/326
