### ISSUE TITLE
Add documentation about nif converter filter

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#328]
[Basic Service Reference](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/basic-services.html)

[API Doc](https://api-dev.freme-project.eu/doc/api-doc/full.html). A short sentence to the nif-converter API endpoint, another one to "informat"

[API Users getting started](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/gettingStarted_API-users.html)

**Comment by bgrusdt** [comment]
This is done. 
* [Api Users Getting started](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-api-users/gettingStarted_API-users.html)
* [NIf-Converter api doc](https://api-dev.freme-project.eu/doc/api-doc/full.html#!/Toolbox%2FNIF-Converter/post_toolbox_nif_converter)

* [Basic services reference](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/basic-services.html#tika-filter)

**Comment by jnehring** [comment]
looks good.
