### ISSUE TITLE
Create documentation user

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#330]
The API documentation uses a user with a certain token. Please create a user named "documentation" and create a token for him. Then in the database in the token table update this token manually and change it to: 74c0359f-b312-48c4-befa-0f3bb6b3090c

Then the interactive parts of the API documentation that require a token will work: https://freme-project.github.io/tutorials/entity-recognition-against-custom-dataset.html

**Comment by munnellg** [comment]
@jnehring This is done and the interactive API documentation now seems to be working

**Comment by jnehring** [comment]
thanks. i tested it and it works.
