### ISSUE TITLE
Make general information collapsible

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#37]
Maybe related to #36

**Comment by jnehring** [comment]
This still needs some more work. I think It should look like this:

```
General Information

Show more
```

By default the general information is hidden and shows only when we click the "show more" button.

I think this needs a modification of the handlebar template. So we will do it together with the other modifications of the handle bar template.

**Comment by ArneBinder** [comment]
moved to https://github.com/freme-project/Documentation/issues/252.
