### ISSUE TITLE
improve e-Entity documentation

### ISSUE THREAD

**Issue by m1ci** [freme-project/freme-project.github.io#47]
For FREME 3.0 we introduce three additional parameters for `POST /e-entity/freme-ner/datasets`
- `description`: short description of the submitted dataset.
- `sparql`: this parameter should be used in combination with the `endpoint` parameter. The value of the `sparql` parameter is a SPARQL query which selects subset of a dataset for import in FREME NER. An example of such query is as follows:

SELECT ?res ?label WHERE { ?res http://www.w3.org/2000/01/rdf-schema#label ?label . ?res http://www.w3.org/1999/02/22-rdf-syntax-ns#type http://dbpedia.org/ontology/Country FILTER ( strstarts(str(?res), "http://dbpedia.org/") ) } ORDER BY ?res LIMIT 500 OFFSET 500'

The query returns a list of triples where the `subject` is the entity URI, and the `object` is the label of the entity. This query returns 500 entities of type Country from DBpedia with their URI and label. This parameter is only valid for FREME NER.
- `endpoint`: a SPARQL endpoint against which the SPARQL query specified with the `sparql` parameter should be executed. The `endpoint` parameter makes sense to use only in combination with the `sparql` parameter. An example of an `endpoint` is `endpoint=http://dbpedia.org/sparql`. This parameter is only valid for FREME NER.
- `numLinks`: the number of links from a knowledge base returned for each entity. Note that for some entities it might returned less links than requested. This might be due to the low number of links available. The default is 1 link per entity. The maximum number of links that can be returned is 5. This parameter is only valid for FREME NER.

**Comment by m1ci** [comment]
please also indicate in the DBpedia Spotlight endpoint that only English is supported. So only `language=en` is valid. Otherwise, an exception is thrown. This solves https://github.com/freme-project/e-Entity/issues/32

**Comment by josauder** [comment]
Does the numLinks parameter work in /e-entity/freme-ner/datasets or /e-entity/freme-ner/documents? A quick glance over the source made it seems like this parameter is only supported in the latter.

**Comment by m1ci** [comment]
Only /documents

On Tuesday, August 25, 2015, josauder notifications@github.com wrote:

> Does the numLinks parameter work in /e-entity/freme-ner/datasets or
> /e-entity/freme-ner/documents? A quick glance over the source made it seems
> like this parameter is only supported in the latter.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/freme-project/Documentation/issues/47#issuecomment-134604062
> .

## 

## 

Milan Dojchinovski
http://dojchinovski.mk

**Comment by josauder** [comment]
What about PUT /e-entity/freme-ner/datasets ? The other three parameters (description, spaql, endpoint) are not in the source code although i guess it would make sense that when updating a dataset one can also change this information. Will they also be added to PUT soon?

**Comment by m1ci** [comment]
> What about PUT /e-entity/freme-ner/datasets ? The other three parameters (description, spaql, endpoint) are not in the source code although i guess it would make sense that when updating a dataset one can also change this information. Will they also be added to PUT soon?

@nilesh-c is this implemented in FREME NER?

**Comment by jnehring** [comment]
@nilesh-c please comment here.

**Comment by jnehring** [comment]
description is in the documentation now.

@bgrusdt please check in FREME NERs source code if the parameters "sparql" and "endpoint" are in the source code of the REST controller for PUT /e-entity/freme-ner/datasets . If yes, please test if they work and if we can add them to the documentation.

**Comment by ArneBinder** [comment]
Seems to be related to https://github.com/freme-project/freme-ner/issues/109.

**Comment by jnehring** [comment]
This issue is a dublicate of https://github.com/freme-project/freme-ner/issues/109
