### ISSUE TITLE
[MS EDGE] Input fields for parameters do not accept multiline values from examples above

### ISSUE THREAD

**Issue by andish** [freme-project/freme-project.github.io#52]
Browser: MS Edge
OS: Windows 10

Steps to reproduce:
1) http://api-dev.freme-project.eu/doc/#!/e-Terminology/tildeTranslate
2) copy NIF example to clipboard
3) paste into 'input' field
4)informat=turtle
5) change target-lang to 'de'

Result:
only first line is copied and service later return 406 error because input data [turtle] not valid.

**Comment by jnehring** [comment]
I think this is ok. I think it is an error of the user when the user sends only the first line of the example. Also I think we cannot do anything here or do you have a solution? I tried with MS Edge in Windows 8 and it does not let me copy a multiline string in the input field.

So @andish can we close this ticket as invalid?

**Comment by andish** [comment]
Initially I was testing e-Publishing and wanted to copy and paste documented sample and try it. This means that this TryItOut webform is unusable from MS EDGE (Maybe also from Internet Explorer) unless the user converts json sample into single line manually. Sample is multiline, but input field not accepting that.
So there are multiple solutions:
- create JavaScript that cleans pasted text from newlines on paste event
- add textarea input field
- add documentation example in single line
- provide button 'copy to clipboard', that places single line sample  into clipboard
- Do nothing and add warning for MS Edge users to be careful

But - this is not critical  issue, you can close as insignificant.

**Comment by jnehring** [comment]
@josauer is it possible to change the `metadata` input field in /e-publishing/html endpoint to a multiline input field / text area?

**Comment by josauder** [comment]
I don't think it is possible to change this only for the `metadata` parameter. I think it would be possible to make all entry fields multiline but I don't think we want that either.

**Comment by ArneBinder** [comment]
I disagree, this is possible. I've implemented it in the swagger-ui branch.
All input fields are textareas now and a parameter can be forced to have a textarea field via the swagger parameter "x-force-textarea: true" in the swagger.yaml.
@jnehring the swagger-ui branch contains the whole swagger-ui Documentation project, not just the html page from the dist folder. Could we switch to this version? This version implements also some other issues (#11 and #37).

**Comment by ArneBinder** [comment]
@josauder can we close this?

**Comment by ArneBinder** [comment]
The `x-force-textarea: true` functionality is broken in the new version merged from swagger-ui-new branch.

**Comment by ArneBinder** [comment]
This works again, but without the additional parameter 'x-force-texarea'. `format: text` triggers the textarea field for a text parameter.
