### ISSUE TITLE
Create 3rd party licensing information for Documentation

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#56]
- Get list of dependencies from source code / html head of http://api-dev.freme-project.eu/doc/
- Add these dependencies to the dependencies spreadsheet and look up their version information
- Create 3rd party license information document for these dependencies

**Comment by ArneBinder** [comment]
Wait for https://github.com/freme-project/Documentation/issues/103

**Comment by ArneBinder** [comment]
finished.

**Comment by jnehring** [comment]
@ArneBinder Did you also update the 3rd party license files in all freme repositories?

**Comment by ArneBinder** [comment]
Yes, it's all up to date.
