### ISSUE TITLE
Add partner logos to start page

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#80]
From [GDrive](https://drive.google.com/drive/folders/0B_Fh3PcCczdRbjdTYTBVdjlaekU)

**Comment by jnehring** [comment]
Please reduce the size of the images and exchange them.

**Comment by jnehring** [comment]
The images dont look good. Some are distorted (Tilde, VistaTEC), the InfAI logo is too small. Also I think the quality should be better.

**Comment by josauder** [comment]
I think the vistatec logo was outdated, I included the new one

**Comment by jnehring** [comment]
There is still something wrong:

![image](https://cloud.githubusercontent.com/assets/10537540/10282472/6abfbd90-6b7b-11e5-982a-ae0361ccdd41.png)

**Comment by josauder** [comment]
fixed
