### ISSUE TITLE
Docu small changes

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#82]
- `<title>` auf allen Seiten zu "FREME Documentation" ändern
- Überschriften bekommen oben einen großen und unten einen mittleren Margin
- http://api-dev.freme-project.eu/doc/knowledge-base/compile-freme-from-source.html -> HTML in XML code beispiel escapen
- Inline code examples sollen eine schwarze anstelle eine roten Schrift haben 
- Die fette zentriert Überschrift kommt raus
- http://api-dev.freme-project.eu/doc/knowledge-base/freme-on-github.html warum werden die Listen nicht als Listen gerendert?
-  How to add Documentation 
  *\* Von GitHub aus beschreiben
  *\* zuerst erklären wie man eine Textänderung macht
  *\* Ein paar Screenshots machen
- Nieves fragen ob wir das EU Logo im Footer brauchen.
- Javascript Error: Mach ein neues Ticket auf und weis es mir zu
- Outgoing links bekommen immer target="_blank" damit sie in neuem Tab öffnen. z.B. auf http://api-dev.freme-project.eu/doc/freme-showcase/ease-of-adaption.html 
- Auf Simple API Documentation:

```
<style>

li#resource_Enrichment_Endpoint{
  display:none;
}

</style>
```

Irgendwie so. Hier geht es darum, die Überschrift "Enrichment Endpoints", die Buttons "Show / Hide", "List Operations", "Expand Operations" und das unten "[Base URL..." auszublenden.

**Comment by josauder** [comment]
# Left Over
- Überschriften bekommen oben einen großen und unten einen mittleren Margin
- Inline code examples sollen eine schwarze anstelle eine roten Schrift haben 
- Die fette zentriert Überschrift kommt raus
-  How to add Documentation 
  *\* Von GitHub aus beschreiben
  *\* zuerst erklären wie man eine Textänderung macht
  *\* Ein paar Screenshots machen
- Nieves fragen ob wir das EU Logo im Footer brauchen. 
- Auf Simple API Documentation:

```
<style>

li#resource_Enrichment_Endpoint{
  display:none;
}

</style>
```

Irgendwie so. Hier geht es darum, die Überschrift "Enrichment Endpoints", die Buttons "Show / Hide", "List Operations", "Expand Operations" und das unten "[Base URL..." auszublenden.

**Comment by josauder** [comment]
# Left Over
-  How to add Documentation 
  -  Von GitHub aus beschreiben
  - zuerst erklären wie man eine Textänderung macht
  - Ein paar Screenshots machen

@jnehring should the line `[ base url: /current , api version: 0.3 ]` only be removed from the simple API-Doc or also the full one?

**Comment by jnehring** [comment]
> should the line [ base url: /current , api version: 0.3 ] only be removed from the simple API-Doc or also the full one?

Good idea, but lets do this when we work on the handle bar templates anyways. I put it on the respective [task list](https://docs.google.com/document/d/1oXd0RYFvd4B22avUMRVJrTYt-7tJ35Bm6tes0hwC398/edit).
