### ISSUE TITLE
Document mode parameter

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#84]
@nilesh-c please provide the text for documentation of the mode parameter.

Then assign the issue to @josauder to implement this in the API documentation.

**Comment by m1ci** [comment]
Please find bellow the description:

The following options are possible

mode=spot
mode=spot,classify
mode=spot,link
mode=spot,link,classify
mode=all (default and same as above)
mode=link (Expects NIF data with entity mentions, i.e. anchorOf, beginIndex, endIndex etc. are given and it does only entity linking.

Note: Order of modes is irrelevant. spot,link,classify is same as spot,classify,link

**Comment by jnehring** [comment]
I update the description to:

The mode parameter allows to produce only partly results of named entity recognition. This can speed up computation time. Spotting and classification are relatively fast operations, whereas linking is a computationally expensive operation. Valid options for mode are:

mode=spot
mode=spot,classify
mode=spot,link
mode=spot,link,classify
mode=all (default and same as above)
mode=link (Expects NIF data with entity mentions, i.e. anchorOf, beginIndex, endIndex etc. are given and it does only entity linking.

Note: Order of modes is irrelevant. spot,link,classify is same as spot,classify,link

**Comment by josauder** [comment]
Closed with cea57a5483f3b48f103fda0017ce8152f1f71be0
