### ISSUE TITLE
Add user authentication

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.io#85]
In the context of [implement template security](https://github.com/freme-project/Broker/issues/107) we need an authentication mechanism to still afford the usability of the eservices E-Link and User via the documentation page.

**Comment by jnehring** [comment]
No we dont implement this now.

**Comment by jnehring** [comment]
It should look like this example from the example pet store. The full documentation should have a input field. When a user puts an API key in the field / when the field is not empty, then the key is attached to every API request in the X-Auth-Token header.

![image](https://cloud.githubusercontent.com/assets/10537540/10367913/3a18bd9a-6dd3-11e5-9306-616a1fe4cb7a.png)

**Comment by josauder** [comment]
I pushed with the added functionality. However I get `no response from server` when I call the Authentication endpoint in order to recieve an access token

```
curl -X POST --header "Content-Type: text/plain" --header "Accept: application/json" --header "X-Auth-Username: asdfasdfdf" --header "X-Auth-Password: asdfasdfasfdg" "http://api-dev.freme-project.eu/current/authenticate"
```

The button still needs styling & a  description or something

**Comment by jnehring** [comment]
I tried the endpoint and it worked:

![image](https://cloud.githubusercontent.com/assets/10537540/10481627/2f5852f0-7272-11e5-9ede-87acc5a5b766.png)

**Comment by jnehring** [comment]
Nice work, thank you. But I have two requests:
- Please remove the token header from the simple api doc.
- In the full api doc, move it to the bottom of the page, under the endpoints. Then add a text: "When you paste your authentication token in this text field then your API calls will be authenticated using this token."
