### ISSUE TITLE
Write documentation for /e-link/explore endpoint

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#90]

**Comment by m1ci** [comment]
Using the /e-link/explore endpoint a client can retrieve description of a resource from a given endpoint. The endpoint can be SPARQL or Linked Data Fragments endpoint. 
The API accepts three parameters:
- `resource` - a URI of the resource which should be described. Note that the URI should be UTF-8 encoded.
- `endpoint` - a URL of the endpoint which should be used to retrieve info about the resource. Note that the URL should be UTF-8 encoded.
- `endpoint-type` - the type of the endpoint. Possible values: `sparql` or `ldf`

**Comment by jnehring** [comment]
@m1ci thanks
@josauder please add a new api endpoint to the full api documentation in e-link as described here.

**Comment by jnehring** [comment]
Thanks. Some updates:
- Please start the parameter descriptions with a capital letter
- Please provide an example. So find a useful example, e.g. explore the resource for berlin in dbpedia
