### ISSUE TITLE
Link to REST API

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-project.github.io#93]
In the homepage, we need a central place to define the URL of the underlying API. So when we do a release we change it only at a single place. Right now we have multiple locations for this information, e.g. one in the list of templates and another one in the API documentations / swagger.yaml.

@josauder  do you have an idea how to implement this?

**Comment by josauder** [comment]
I can do this with jekyll if I move the js file into Html-Inline-Javascript.
See the _pages/apidoc/list-templates.html in the current commit.
The URI is correctly rendered by jekyll but I get a JS error for cross-site requests. Im working on it now.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://api-dev.freme-project.eu/e-link/templates. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

**Comment by josauder** [comment]
Oh, seems to work on api-dev.freme-project.eu/doc/api-doc/list-templates.html
Just not on localhost.

Now the only place where the URI is defined is in the _config.yml (for the listing of templates - I'm sure there is a smiliar way to do this for the Swager-Api-Doc)

**Comment by jnehring** [comment]
Please do not implement this right away but lets discuss it first. So you can specify the URL as inline javascript, e.g. in the jekyll template somewhere on top of the page in the `<head>` tag.

Can you pass this URL to Swagger or does that mean we have to specify the URL in two places: Once in the jekyll template and once in the swagger.yaml?

**Comment by jnehring** [comment]
It is not possible right now to have one single API Url. So we will have two:
- One in swagger.yaml. This does not require any changes.
- One in the swagger config file (_config.yaml) that is written in the html head of each page. From this place it can be used in all JS codes. This is done, but the URL needs to be changed to http://api-dev.freme-project.eu/current

So the next steps in this issue are:
- Change URL (as written above in this post)
- Update the Javascripts to use this URI in all three showroom pages.
- Put this in the [release documentation](https://github.com/freme-project/technical-discussion/wiki/Release-Howto#3-release-of-api-documentation). It introduces two new steps: Change URLs to the live version before the release and change it back to the development version after the release.
