### ISSUE TITLE
Article about e-Internationalization

### ISSUE THREAD

**Issue by borriellom** [freme-project/freme-project.github.io#95]
Create an article about e-Internationalization service accessible from the Knowledge Base drop down menu.

**Comment by jnehring** [comment]
Some information about how to call the e-Internationalization functions in the REST API:

e-Internationalization can convert an input document to NIF. In that case you have to specify the input format, either in the `informat` query string parameter or the `Content-Type` header. When both are specified then the `informat` header overwrites the `Content-Type` header. You can specify an RDF output format to get the output in NIF. When no output format is specified the service will return turtle.

You can also use the service for roundtripping conversion. That means you can convert the input format to NIF and then back to the original input format. To do so you have to specify the output format. E.g. you can specify `informat=text/html` and `outformat=text/html` to do html5 roundtripping. Please note that the outformat has to be the same like the input format for roundtripping.

**Comment by m1ci** [comment]
its documented here http://api-dev.freme-project.eu/doc/knowledge-base/eInternationalization.html

**Comment by jnehring** [comment]
Nice article. Some small improvements: 
- It is so long, can you please add a table of contents?
- The text "For the sake of completeness, below are the lists of supported ITS 2.0 categories for each format.". I propose to say "Below are the lists of ITS 2.0 categories that are transported from the original format to NIF. They are also transported from NIF back to the original format when e-Internationalization supports roundtripping for this format."

Then IMO we can close this issue
