### ISSUE TITLE
In the documentation show only verified templates

### ISSUE THREAD

**Issue by m1ci** [freme-project/freme-project.github.io#98]
Currently, the list of templates is very long with a lot of invalid templates.
http://api-dev.freme-project.eu/doc/api-doc/list-templates.html
I suggest we show only templates verified - created by the `admin` user.

**Comment by jnehring** [comment]
You are right there is a lot of trash. We need to find a good concept for the templates. The idea of the templates is that users can share their templates. Unfortunately right now this does not happen.

A good start might be to have well documented and verified templates on the documentation homepage: http://api-dev.freme-project.eu/doc/api-doc/list-templates.html

**Comment by m1ci** [comment]
yes, showing only the verified template at the documentation page, while returning all templates via the API.

**Comment by josauder** [comment]
The Api-Dev version looks especially bad because the same template is in the database ~3000x

**Comment by jnehring** [comment]
Next developer call we will announce to delete all templates not created by admin on api-dev. I can do this with one SQL command.

We should wait until next developers call to make sure not to delete any important data.
